set SynModuleInfo {
  {SRCNAME main_Pipeline_VITIS_LOOP_21_1 MODELNAME main_Pipeline_VITIS_LOOP_21_1 RTLNAME main_main_Pipeline_VITIS_LOOP_21_1
    SUBMODULES {
      {MODELNAME main_mux_32_32_1_1 RTLNAME main_mux_32_32_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME main_flow_control_loop_pipe_sequential_init RTLNAME main_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME main_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME main_Pipeline_VITIS_LOOP_21_125 MODELNAME main_Pipeline_VITIS_LOOP_21_125 RTLNAME main_main_Pipeline_VITIS_LOOP_21_125}
  {SRCNAME main_Pipeline_VITIS_LOOP_21_126 MODELNAME main_Pipeline_VITIS_LOOP_21_126 RTLNAME main_main_Pipeline_VITIS_LOOP_21_126}
  {SRCNAME main_Pipeline_VITIS_LOOP_21_127 MODELNAME main_Pipeline_VITIS_LOOP_21_127 RTLNAME main_main_Pipeline_VITIS_LOOP_21_127}
  {SRCNAME main_Pipeline_VITIS_LOOP_21_128 MODELNAME main_Pipeline_VITIS_LOOP_21_128 RTLNAME main_main_Pipeline_VITIS_LOOP_21_128}
  {SRCNAME main_Pipeline_VITIS_LOOP_21_129 MODELNAME main_Pipeline_VITIS_LOOP_21_129 RTLNAME main_main_Pipeline_VITIS_LOOP_21_129}
  {SRCNAME main_Pipeline_VITIS_LOOP_21_130 MODELNAME main_Pipeline_VITIS_LOOP_21_130 RTLNAME main_main_Pipeline_VITIS_LOOP_21_130}
  {SRCNAME main_Pipeline_VITIS_LOOP_21_131 MODELNAME main_Pipeline_VITIS_LOOP_21_131 RTLNAME main_main_Pipeline_VITIS_LOOP_21_131}
  {SRCNAME main_Pipeline_VITIS_LOOP_21_132 MODELNAME main_Pipeline_VITIS_LOOP_21_132 RTLNAME main_main_Pipeline_VITIS_LOOP_21_132}
  {SRCNAME main_Pipeline_VITIS_LOOP_21_133 MODELNAME main_Pipeline_VITIS_LOOP_21_133 RTLNAME main_main_Pipeline_VITIS_LOOP_21_133}
  {SRCNAME main_Pipeline_VITIS_LOOP_21_134 MODELNAME main_Pipeline_VITIS_LOOP_21_134 RTLNAME main_main_Pipeline_VITIS_LOOP_21_134}
  {SRCNAME main_Pipeline_VITIS_LOOP_21_135 MODELNAME main_Pipeline_VITIS_LOOP_21_135 RTLNAME main_main_Pipeline_VITIS_LOOP_21_135}
  {SRCNAME main_Pipeline_VITIS_LOOP_45_1 MODELNAME main_Pipeline_VITIS_LOOP_45_1 RTLNAME main_main_Pipeline_VITIS_LOOP_45_1}
  {SRCNAME sqrt MODELNAME sqrt RTLNAME main_sqrt
    SUBMODULES {
      {MODELNAME main_fsqrt_32ns_32ns_32_8_no_dsp_1 RTLNAME main_fsqrt_32ns_32ns_32_8_no_dsp_1 BINDTYPE op TYPE fsqrt IMPL fabric LATENCY 7 ALLOW_PRAGMA 1}
      {MODELNAME main_sqrt_aux_RAM_AUTO_1R1W RTLNAME main_sqrt_aux_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME _sum_Pipeline_VITIS_LOOP_84_1 MODELNAME p_sum_Pipeline_VITIS_LOOP_84_1 RTLNAME main_p_sum_Pipeline_VITIS_LOOP_84_1}
  {SRCNAME _sum_Pipeline_VITIS_LOOP_92_2 MODELNAME p_sum_Pipeline_VITIS_LOOP_92_2 RTLNAME main_p_sum_Pipeline_VITIS_LOOP_92_2}
  {SRCNAME _sum_Pipeline_VITIS_LOOP_104_3 MODELNAME p_sum_Pipeline_VITIS_LOOP_104_3 RTLNAME main_p_sum_Pipeline_VITIS_LOOP_104_3}
  {SRCNAME _sum MODELNAME p_sum RTLNAME main_p_sum}
  {SRCNAME operator+ MODELNAME operator_add RTLNAME main_operator_add}
  {SRCNAME _sum.1_Pipeline_VITIS_LOOP_84_1 MODELNAME p_sum_1_Pipeline_VITIS_LOOP_84_1 RTLNAME main_p_sum_1_Pipeline_VITIS_LOOP_84_1}
  {SRCNAME _sum.1_Pipeline_VITIS_LOOP_92_2 MODELNAME p_sum_1_Pipeline_VITIS_LOOP_92_2 RTLNAME main_p_sum_1_Pipeline_VITIS_LOOP_92_2}
  {SRCNAME _sum.1_Pipeline_VITIS_LOOP_104_3 MODELNAME p_sum_1_Pipeline_VITIS_LOOP_104_3 RTLNAME main_p_sum_1_Pipeline_VITIS_LOOP_104_3}
  {SRCNAME _sum.1 MODELNAME p_sum_1 RTLNAME main_p_sum_1}
  {SRCNAME operator+.2_Pipeline_VITIS_LOOP_84_1 MODELNAME operator_2_Pipeline_VITIS_LOOP_84_1 RTLNAME main_operator_2_Pipeline_VITIS_LOOP_84_1}
  {SRCNAME operator+.2_Pipeline_VITIS_LOOP_92_2 MODELNAME operator_2_Pipeline_VITIS_LOOP_92_2 RTLNAME main_operator_2_Pipeline_VITIS_LOOP_92_2}
  {SRCNAME operator+.2_Pipeline_VITIS_LOOP_104_3 MODELNAME operator_2_Pipeline_VITIS_LOOP_104_3 RTLNAME main_operator_2_Pipeline_VITIS_LOOP_104_3}
  {SRCNAME operator+.2 MODELNAME operator_2 RTLNAME main_operator_2}
  {SRCNAME mul_body_Pipeline_VITIS_LOOP_84_1 MODELNAME mul_body_Pipeline_VITIS_LOOP_84_1 RTLNAME main_mul_body_Pipeline_VITIS_LOOP_84_1}
  {SRCNAME mul_body_Pipeline_VITIS_LOOP_92_2 MODELNAME mul_body_Pipeline_VITIS_LOOP_92_2 RTLNAME main_mul_body_Pipeline_VITIS_LOOP_92_2}
  {SRCNAME mul_body_Pipeline_VITIS_LOOP_104_3 MODELNAME mul_body_Pipeline_VITIS_LOOP_104_3 RTLNAME main_mul_body_Pipeline_VITIS_LOOP_104_3}
  {SRCNAME mul_body MODELNAME mul_body RTLNAME main_mul_body}
  {SRCNAME _mul MODELNAME p_mul RTLNAME main_p_mul}
  {SRCNAME _mul.161 MODELNAME p_mul_161 RTLNAME main_p_mul_161}
  {SRCNAME operator/.1.1_Pipeline_VITIS_LOOP_84_1 MODELNAME operator_1_1_Pipeline_VITIS_LOOP_84_1 RTLNAME main_operator_1_1_Pipeline_VITIS_LOOP_84_1}
  {SRCNAME operator/.1.1_Pipeline_VITIS_LOOP_92_2 MODELNAME operator_1_1_Pipeline_VITIS_LOOP_92_2 RTLNAME main_operator_1_1_Pipeline_VITIS_LOOP_92_2}
  {SRCNAME operator/.1.1_Pipeline_VITIS_LOOP_104_3 MODELNAME operator_1_1_Pipeline_VITIS_LOOP_104_3 RTLNAME main_operator_1_1_Pipeline_VITIS_LOOP_104_3}
  {SRCNAME operator/.1.1 MODELNAME operator_1_1 RTLNAME main_operator_1_1}
  {SRCNAME main_Pipeline_VITIS_LOOP_53_1 MODELNAME main_Pipeline_VITIS_LOOP_53_1 RTLNAME main_main_Pipeline_VITIS_LOOP_53_1}
  {SRCNAME main_Pipeline_VITIS_LOOP_458_1 MODELNAME main_Pipeline_VITIS_LOOP_458_1 RTLNAME main_main_Pipeline_VITIS_LOOP_458_1}
  {SRCNAME operator+.1_Pipeline_VITIS_LOOP_84_1 MODELNAME operator_1_Pipeline_VITIS_LOOP_84_1 RTLNAME main_operator_1_Pipeline_VITIS_LOOP_84_1}
  {SRCNAME operator+.1_Pipeline_VITIS_LOOP_92_2 MODELNAME operator_1_Pipeline_VITIS_LOOP_92_2 RTLNAME main_operator_1_Pipeline_VITIS_LOOP_92_2}
  {SRCNAME operator+.1_Pipeline_VITIS_LOOP_104_3 MODELNAME operator_1_Pipeline_VITIS_LOOP_104_3 RTLNAME main_operator_1_Pipeline_VITIS_LOOP_104_3}
  {SRCNAME operator+.1_Pipeline_VITIS_LOOP_627_1 MODELNAME operator_1_Pipeline_VITIS_LOOP_627_1 RTLNAME main_operator_1_Pipeline_VITIS_LOOP_627_1}
  {SRCNAME operator+.1_Pipeline_VITIS_LOOP_21_1 MODELNAME operator_1_Pipeline_VITIS_LOOP_21_1 RTLNAME main_operator_1_Pipeline_VITIS_LOOP_21_1}
  {SRCNAME operator+.1 MODELNAME operator_1 RTLNAME main_operator_1}
  {SRCNAME main_Pipeline_VITIS_LOOP_84_1 MODELNAME main_Pipeline_VITIS_LOOP_84_1 RTLNAME main_main_Pipeline_VITIS_LOOP_84_1}
  {SRCNAME main_Pipeline_VITIS_LOOP_92_2 MODELNAME main_Pipeline_VITIS_LOOP_92_2 RTLNAME main_main_Pipeline_VITIS_LOOP_92_2}
  {SRCNAME main_Pipeline_VITIS_LOOP_104_3 MODELNAME main_Pipeline_VITIS_LOOP_104_3 RTLNAME main_main_Pipeline_VITIS_LOOP_104_3}
  {SRCNAME operator/.1.2_Pipeline_VITIS_LOOP_84_1 MODELNAME operator_1_2_Pipeline_VITIS_LOOP_84_1 RTLNAME main_operator_1_2_Pipeline_VITIS_LOOP_84_1}
  {SRCNAME operator/.1.2_Pipeline_VITIS_LOOP_92_2 MODELNAME operator_1_2_Pipeline_VITIS_LOOP_92_2 RTLNAME main_operator_1_2_Pipeline_VITIS_LOOP_92_2}
  {SRCNAME operator/.1.2_Pipeline_VITIS_LOOP_104_3 MODELNAME operator_1_2_Pipeline_VITIS_LOOP_104_3 RTLNAME main_operator_1_2_Pipeline_VITIS_LOOP_104_3}
  {SRCNAME operator/.1.2 MODELNAME operator_1_2 RTLNAME main_operator_1_2}
  {SRCNAME operator/_Pipeline_VITIS_LOOP_84_1 MODELNAME operator_Pipeline_VITIS_LOOP_84_1 RTLNAME main_operator_Pipeline_VITIS_LOOP_84_1}
  {SRCNAME operator/_Pipeline_VITIS_LOOP_92_2 MODELNAME operator_Pipeline_VITIS_LOOP_92_2 RTLNAME main_operator_Pipeline_VITIS_LOOP_92_2}
  {SRCNAME operator/_Pipeline_VITIS_LOOP_104_3 MODELNAME operator_Pipeline_VITIS_LOOP_104_3 RTLNAME main_operator_Pipeline_VITIS_LOOP_104_3}
  {SRCNAME operator/ MODELNAME operator_div RTLNAME main_operator_div}
  {SRCNAME main_Pipeline_VITIS_LOOP_68_1 MODELNAME main_Pipeline_VITIS_LOOP_68_1 RTLNAME main_main_Pipeline_VITIS_LOOP_68_1}
  {SRCNAME main_Pipeline_VITIS_LOOP_497_1 MODELNAME main_Pipeline_VITIS_LOOP_497_1 RTLNAME main_main_Pipeline_VITIS_LOOP_497_1}
  {SRCNAME main_Pipeline_VITIS_LOOP_311_1 MODELNAME main_Pipeline_VITIS_LOOP_311_1 RTLNAME main_main_Pipeline_VITIS_LOOP_311_1}
  {SRCNAME main_Pipeline_VITIS_LOOP_315_2 MODELNAME main_Pipeline_VITIS_LOOP_315_2 RTLNAME main_main_Pipeline_VITIS_LOOP_315_2}
  {SRCNAME main_Pipeline_VITIS_LOOP_84_136 MODELNAME main_Pipeline_VITIS_LOOP_84_136 RTLNAME main_main_Pipeline_VITIS_LOOP_84_136}
  {SRCNAME main_Pipeline_VITIS_LOOP_92_237 MODELNAME main_Pipeline_VITIS_LOOP_92_237 RTLNAME main_main_Pipeline_VITIS_LOOP_92_237}
  {SRCNAME main_Pipeline_VITIS_LOOP_104_338 MODELNAME main_Pipeline_VITIS_LOOP_104_338 RTLNAME main_main_Pipeline_VITIS_LOOP_104_338}
  {SRCNAME main_Pipeline_VITIS_LOOP_311_139 MODELNAME main_Pipeline_VITIS_LOOP_311_139 RTLNAME main_main_Pipeline_VITIS_LOOP_311_139}
  {SRCNAME main_Pipeline_VITIS_LOOP_315_240 MODELNAME main_Pipeline_VITIS_LOOP_315_240 RTLNAME main_main_Pipeline_VITIS_LOOP_315_240}
  {SRCNAME main_Pipeline_VITIS_LOOP_84_141 MODELNAME main_Pipeline_VITIS_LOOP_84_141 RTLNAME main_main_Pipeline_VITIS_LOOP_84_141}
  {SRCNAME main_Pipeline_VITIS_LOOP_92_242 MODELNAME main_Pipeline_VITIS_LOOP_92_242 RTLNAME main_main_Pipeline_VITIS_LOOP_92_242}
  {SRCNAME main_Pipeline_VITIS_LOOP_104_343 MODELNAME main_Pipeline_VITIS_LOOP_104_343 RTLNAME main_main_Pipeline_VITIS_LOOP_104_343}
  {SRCNAME main_Pipeline_VITIS_LOOP_169_1 MODELNAME main_Pipeline_VITIS_LOOP_169_1 RTLNAME main_main_Pipeline_VITIS_LOOP_169_1}
  {SRCNAME main_Pipeline_VITIS_LOOP_187_1 MODELNAME main_Pipeline_VITIS_LOOP_187_1 RTLNAME main_main_Pipeline_VITIS_LOOP_187_1}
  {SRCNAME main_Pipeline_VITIS_LOOP_84_144 MODELNAME main_Pipeline_VITIS_LOOP_84_144 RTLNAME main_main_Pipeline_VITIS_LOOP_84_144}
  {SRCNAME main_Pipeline_VITIS_LOOP_92_245 MODELNAME main_Pipeline_VITIS_LOOP_92_245 RTLNAME main_main_Pipeline_VITIS_LOOP_92_245}
  {SRCNAME main_Pipeline_VITIS_LOOP_104_346 MODELNAME main_Pipeline_VITIS_LOOP_104_346 RTLNAME main_main_Pipeline_VITIS_LOOP_104_346}
  {SRCNAME main_Pipeline_VITIS_LOOP_215_1 MODELNAME main_Pipeline_VITIS_LOOP_215_1 RTLNAME main_main_Pipeline_VITIS_LOOP_215_1}
  {SRCNAME _mul.1 MODELNAME p_mul_1 RTLNAME main_p_mul_1}
  {SRCNAME main_Pipeline_VITIS_LOOP_84_147 MODELNAME main_Pipeline_VITIS_LOOP_84_147 RTLNAME main_main_Pipeline_VITIS_LOOP_84_147}
  {SRCNAME main_Pipeline_VITIS_LOOP_92_248 MODELNAME main_Pipeline_VITIS_LOOP_92_248 RTLNAME main_main_Pipeline_VITIS_LOOP_92_248}
  {SRCNAME main_Pipeline_VITIS_LOOP_104_349 MODELNAME main_Pipeline_VITIS_LOOP_104_349 RTLNAME main_main_Pipeline_VITIS_LOOP_104_349}
  {SRCNAME main_Pipeline_VITIS_LOOP_84_150 MODELNAME main_Pipeline_VITIS_LOOP_84_150 RTLNAME main_main_Pipeline_VITIS_LOOP_84_150}
  {SRCNAME main_Pipeline_VITIS_LOOP_92_251 MODELNAME main_Pipeline_VITIS_LOOP_92_251 RTLNAME main_main_Pipeline_VITIS_LOOP_92_251}
  {SRCNAME main_Pipeline_VITIS_LOOP_104_352 MODELNAME main_Pipeline_VITIS_LOOP_104_352 RTLNAME main_main_Pipeline_VITIS_LOOP_104_352}
  {SRCNAME main_Pipeline_VITIS_LOOP_627_1 MODELNAME main_Pipeline_VITIS_LOOP_627_1 RTLNAME main_main_Pipeline_VITIS_LOOP_627_1}
  {SRCNAME main_Pipeline_VITIS_LOOP_84_153 MODELNAME main_Pipeline_VITIS_LOOP_84_153 RTLNAME main_main_Pipeline_VITIS_LOOP_84_153}
  {SRCNAME main_Pipeline_VITIS_LOOP_92_254 MODELNAME main_Pipeline_VITIS_LOOP_92_254 RTLNAME main_main_Pipeline_VITIS_LOOP_92_254}
  {SRCNAME main_Pipeline_VITIS_LOOP_104_355 MODELNAME main_Pipeline_VITIS_LOOP_104_355 RTLNAME main_main_Pipeline_VITIS_LOOP_104_355}
  {SRCNAME main_Pipeline_VITIS_LOOP_627_156 MODELNAME main_Pipeline_VITIS_LOOP_627_156 RTLNAME main_main_Pipeline_VITIS_LOOP_627_156}
  {SRCNAME main_Pipeline_VITIS_LOOP_84_157 MODELNAME main_Pipeline_VITIS_LOOP_84_157 RTLNAME main_main_Pipeline_VITIS_LOOP_84_157}
  {SRCNAME main_Pipeline_VITIS_LOOP_92_258 MODELNAME main_Pipeline_VITIS_LOOP_92_258 RTLNAME main_main_Pipeline_VITIS_LOOP_92_258}
  {SRCNAME main_Pipeline_VITIS_LOOP_104_359 MODELNAME main_Pipeline_VITIS_LOOP_104_359 RTLNAME main_main_Pipeline_VITIS_LOOP_104_359}
  {SRCNAME main_Pipeline_VITIS_LOOP_84_160 MODELNAME main_Pipeline_VITIS_LOOP_84_160 RTLNAME main_main_Pipeline_VITIS_LOOP_84_160}
  {SRCNAME main_Pipeline_VITIS_LOOP_92_261 MODELNAME main_Pipeline_VITIS_LOOP_92_261 RTLNAME main_main_Pipeline_VITIS_LOOP_92_261}
  {SRCNAME main_Pipeline_VITIS_LOOP_104_362 MODELNAME main_Pipeline_VITIS_LOOP_104_362 RTLNAME main_main_Pipeline_VITIS_LOOP_104_362}
  {SRCNAME main_Pipeline_VITIS_LOOP_21_163 MODELNAME main_Pipeline_VITIS_LOOP_21_163 RTLNAME main_main_Pipeline_VITIS_LOOP_21_163}
  {SRCNAME main_Pipeline_VITIS_LOOP_21_164 MODELNAME main_Pipeline_VITIS_LOOP_21_164 RTLNAME main_main_Pipeline_VITIS_LOOP_21_164}
  {SRCNAME main_Pipeline_VITIS_LOOP_21_165 MODELNAME main_Pipeline_VITIS_LOOP_21_165 RTLNAME main_main_Pipeline_VITIS_LOOP_21_165}
  {SRCNAME mul_body.1_Pipeline_VITIS_LOOP_169_1 MODELNAME mul_body_1_Pipeline_VITIS_LOOP_169_1 RTLNAME main_mul_body_1_Pipeline_VITIS_LOOP_169_1}
  {SRCNAME mul_body.1_Pipeline_VITIS_LOOP_187_1 MODELNAME mul_body_1_Pipeline_VITIS_LOOP_187_1 RTLNAME main_mul_body_1_Pipeline_VITIS_LOOP_187_1}
  {SRCNAME mul_body.1_Pipeline_VITIS_LOOP_21_1 MODELNAME mul_body_1_Pipeline_VITIS_LOOP_21_1 RTLNAME main_mul_body_1_Pipeline_VITIS_LOOP_21_1}
  {SRCNAME mul_body.1_Pipeline_VITIS_LOOP_84_1 MODELNAME mul_body_1_Pipeline_VITIS_LOOP_84_1 RTLNAME main_mul_body_1_Pipeline_VITIS_LOOP_84_1}
  {SRCNAME mul_body.1_Pipeline_VITIS_LOOP_92_2 MODELNAME mul_body_1_Pipeline_VITIS_LOOP_92_2 RTLNAME main_mul_body_1_Pipeline_VITIS_LOOP_92_2}
  {SRCNAME mul_body.1_Pipeline_VITIS_LOOP_104_3 MODELNAME mul_body_1_Pipeline_VITIS_LOOP_104_3 RTLNAME main_mul_body_1_Pipeline_VITIS_LOOP_104_3}
  {SRCNAME mul_body.1 MODELNAME mul_body_1 RTLNAME main_mul_body_1}
  {SRCNAME main_Pipeline_VITIS_LOOP_169_166 MODELNAME main_Pipeline_VITIS_LOOP_169_166 RTLNAME main_main_Pipeline_VITIS_LOOP_169_166}
  {SRCNAME main_Pipeline_VITIS_LOOP_187_167 MODELNAME main_Pipeline_VITIS_LOOP_187_167 RTLNAME main_main_Pipeline_VITIS_LOOP_187_167}
  {SRCNAME main_Pipeline_VITIS_LOOP_84_168 MODELNAME main_Pipeline_VITIS_LOOP_84_168 RTLNAME main_main_Pipeline_VITIS_LOOP_84_168}
  {SRCNAME main_Pipeline_VITIS_LOOP_92_269 MODELNAME main_Pipeline_VITIS_LOOP_92_269 RTLNAME main_main_Pipeline_VITIS_LOOP_92_269}
  {SRCNAME main_Pipeline_VITIS_LOOP_104_370 MODELNAME main_Pipeline_VITIS_LOOP_104_370 RTLNAME main_main_Pipeline_VITIS_LOOP_104_370}
  {SRCNAME main_Pipeline_VITIS_LOOP_21_171 MODELNAME main_Pipeline_VITIS_LOOP_21_171 RTLNAME main_main_Pipeline_VITIS_LOOP_21_171}
  {SRCNAME operator/.1_Pipeline_VITIS_LOOP_21_1 MODELNAME operator_1_Pipeline_VITIS_LOOP_21_1_s RTLNAME main_operator_1_Pipeline_VITIS_LOOP_21_1_s}
  {SRCNAME operator/.1_Pipeline_VITIS_LOOP_791_1 MODELNAME operator_1_Pipeline_VITIS_LOOP_791_1 RTLNAME main_operator_1_Pipeline_VITIS_LOOP_791_1}
  {SRCNAME operator/.1_Pipeline_VITIS_LOOP_34_1 MODELNAME operator_1_Pipeline_VITIS_LOOP_34_1 RTLNAME main_operator_1_Pipeline_VITIS_LOOP_34_1}
  {SRCNAME operator/.1_Pipeline_VITIS_LOOP_169_1 MODELNAME operator_1_Pipeline_VITIS_LOOP_169_1 RTLNAME main_operator_1_Pipeline_VITIS_LOOP_169_1}
  {SRCNAME operator/.1_Pipeline_VITIS_LOOP_187_1 MODELNAME operator_1_Pipeline_VITIS_LOOP_187_1 RTLNAME main_operator_1_Pipeline_VITIS_LOOP_187_1}
  {SRCNAME operator/.1_Pipeline_VITIS_LOOP_169_123 MODELNAME operator_1_Pipeline_VITIS_LOOP_169_123 RTLNAME main_operator_1_Pipeline_VITIS_LOOP_169_123}
  {SRCNAME operator/.1_Pipeline_VITIS_LOOP_187_124 MODELNAME operator_1_Pipeline_VITIS_LOOP_187_124 RTLNAME main_operator_1_Pipeline_VITIS_LOOP_187_124}
  {SRCNAME operator/.1_Pipeline_VITIS_LOOP_84_1 MODELNAME operator_1_Pipeline_VITIS_LOOP_84_1_s RTLNAME main_operator_1_Pipeline_VITIS_LOOP_84_1_s}
  {SRCNAME operator/.1_Pipeline_VITIS_LOOP_92_2 MODELNAME operator_1_Pipeline_VITIS_LOOP_92_2_s RTLNAME main_operator_1_Pipeline_VITIS_LOOP_92_2_s}
  {SRCNAME operator/.1_Pipeline_VITIS_LOOP_104_3 MODELNAME operator_1_Pipeline_VITIS_LOOP_104_3_s RTLNAME main_operator_1_Pipeline_VITIS_LOOP_104_3_s}
  {SRCNAME operator/.1 MODELNAME operator_1_s RTLNAME main_operator_1_s}
  {SRCNAME operator/.2_Pipeline_VITIS_LOOP_215_1 MODELNAME operator_2_Pipeline_VITIS_LOOP_215_1 RTLNAME main_operator_2_Pipeline_VITIS_LOOP_215_1}
  {SRCNAME operator/.2_Pipeline_VITIS_LOOP_84_1 MODELNAME operator_2_Pipeline_VITIS_LOOP_84_1_s RTLNAME main_operator_2_Pipeline_VITIS_LOOP_84_1_s}
  {SRCNAME operator/.2_Pipeline_VITIS_LOOP_92_2 MODELNAME operator_2_Pipeline_VITIS_LOOP_92_2_s RTLNAME main_operator_2_Pipeline_VITIS_LOOP_92_2_s}
  {SRCNAME operator/.2_Pipeline_VITIS_LOOP_104_3 MODELNAME operator_2_Pipeline_VITIS_LOOP_104_3_s RTLNAME main_operator_2_Pipeline_VITIS_LOOP_104_3_s}
  {SRCNAME operator/.2 MODELNAME operator_2_s RTLNAME main_operator_2_s}
  {SRCNAME main_Pipeline_VITIS_LOOP_362_1 MODELNAME main_Pipeline_VITIS_LOOP_362_1 RTLNAME main_main_Pipeline_VITIS_LOOP_362_1}
  {SRCNAME main_Pipeline_VITIS_LOOP_169_172 MODELNAME main_Pipeline_VITIS_LOOP_169_172 RTLNAME main_main_Pipeline_VITIS_LOOP_169_172}
  {SRCNAME main_Pipeline_VITIS_LOOP_187_173 MODELNAME main_Pipeline_VITIS_LOOP_187_173 RTLNAME main_main_Pipeline_VITIS_LOOP_187_173}
  {SRCNAME main_Pipeline_VITIS_LOOP_84_174 MODELNAME main_Pipeline_VITIS_LOOP_84_174 RTLNAME main_main_Pipeline_VITIS_LOOP_84_174}
  {SRCNAME main_Pipeline_VITIS_LOOP_92_275 MODELNAME main_Pipeline_VITIS_LOOP_92_275 RTLNAME main_main_Pipeline_VITIS_LOOP_92_275}
  {SRCNAME main_Pipeline_VITIS_LOOP_104_376 MODELNAME main_Pipeline_VITIS_LOOP_104_376 RTLNAME main_main_Pipeline_VITIS_LOOP_104_376}
  {SRCNAME main_Pipeline_VITIS_LOOP_84_177 MODELNAME main_Pipeline_VITIS_LOOP_84_177 RTLNAME main_main_Pipeline_VITIS_LOOP_84_177}
  {SRCNAME main_Pipeline_VITIS_LOOP_92_278 MODELNAME main_Pipeline_VITIS_LOOP_92_278 RTLNAME main_main_Pipeline_VITIS_LOOP_92_278}
  {SRCNAME main_Pipeline_VITIS_LOOP_104_379 MODELNAME main_Pipeline_VITIS_LOOP_104_379 RTLNAME main_main_Pipeline_VITIS_LOOP_104_379}
  {SRCNAME main_Pipeline_VITIS_LOOP_44_1 MODELNAME main_Pipeline_VITIS_LOOP_44_1 RTLNAME main_main_Pipeline_VITIS_LOOP_44_1}
  {SRCNAME _sum.2_Pipeline_VITIS_LOOP_84_1 MODELNAME p_sum_2_Pipeline_VITIS_LOOP_84_1 RTLNAME main_p_sum_2_Pipeline_VITIS_LOOP_84_1}
  {SRCNAME _sum.2_Pipeline_VITIS_LOOP_92_2 MODELNAME p_sum_2_Pipeline_VITIS_LOOP_92_2 RTLNAME main_p_sum_2_Pipeline_VITIS_LOOP_92_2}
  {SRCNAME _sum.2_Pipeline_VITIS_LOOP_104_3 MODELNAME p_sum_2_Pipeline_VITIS_LOOP_104_3 RTLNAME main_p_sum_2_Pipeline_VITIS_LOOP_104_3}
  {SRCNAME _sum.2 MODELNAME p_sum_2 RTLNAME main_p_sum_2}
  {SRCNAME operator+.3 MODELNAME operator_3 RTLNAME main_operator_3}
  {SRCNAME main MODELNAME main RTLNAME main IS_TOP 1
    SUBMODULES {
      {MODELNAME main_faddfsub_32ns_32ns_32_4_full_dsp_1 RTLNAME main_faddfsub_32ns_32ns_32_4_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME main_fadd_32ns_32ns_32_4_full_dsp_1 RTLNAME main_fadd_32ns_32ns_32_4_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME main_fmul_32ns_32ns_32_3_max_dsp_1 RTLNAME main_fmul_32ns_32ns_32_3_max_dsp_1 BINDTYPE op TYPE fmul IMPL maxdsp LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME main_fdiv_32ns_32ns_32_9_no_dsp_1 RTLNAME main_fdiv_32ns_32ns_32_9_no_dsp_1 BINDTYPE op TYPE fdiv IMPL fabric LATENCY 8 ALLOW_PRAGMA 1}
      {MODELNAME main_uitofp_32ns_32_4_no_dsp_1 RTLNAME main_uitofp_32ns_32_4_no_dsp_1 BINDTYPE op TYPE uitofp IMPL auto LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME main_fcmp_32ns_32ns_1_2_no_dsp_1 RTLNAME main_fcmp_32ns_32ns_1_2_no_dsp_1 BINDTYPE op TYPE fcmp IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME main_v_ROM_AUTO_1R RTLNAME main_v_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME main_b_p_RAM_AUTO_1R1W RTLNAME main_b_p_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME main_b_num_RAM_1WNR_AUTO_1R1W RTLNAME main_b_num_RAM_1WNR_AUTO_1R1W BINDTYPE storage TYPE ram_1wnr IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME main_r_p_RAM_AUTO_1R1W RTLNAME main_r_p_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME main_r_num_RAM_AUTO_1R1W RTLNAME main_r_num_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
}
