set SynModuleInfo {
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_410_122 MODELNAME ban_interface_Pipeline_VITIS_LOOP_410_122 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_410_122
    SUBMODULES {
      {MODELNAME ban_interface_flow_control_loop_pipe_sequential_init RTLNAME ban_interface_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME ban_interface_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_374_121 MODELNAME ban_interface_Pipeline_VITIS_LOOP_374_121 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_374_121}
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_410_120 MODELNAME ban_interface_Pipeline_VITIS_LOOP_410_120 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_410_120}
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_374_119 MODELNAME ban_interface_Pipeline_VITIS_LOOP_374_119 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_374_119}
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_68_118 MODELNAME ban_interface_Pipeline_VITIS_LOOP_68_118 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_68_118}
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_68_117 MODELNAME ban_interface_Pipeline_VITIS_LOOP_68_117 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_68_117}
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_374_116 MODELNAME ban_interface_Pipeline_VITIS_LOOP_374_116 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_374_116}
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_410_115 MODELNAME ban_interface_Pipeline_VITIS_LOOP_410_115 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_410_115}
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_410_1 MODELNAME ban_interface_Pipeline_VITIS_LOOP_410_1 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_410_1}
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_374_1 MODELNAME ban_interface_Pipeline_VITIS_LOOP_374_1 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_374_1}
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_68_114 MODELNAME ban_interface_Pipeline_VITIS_LOOP_68_114 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_68_114}
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_68_1 MODELNAME ban_interface_Pipeline_VITIS_LOOP_68_1 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_68_1}
  {SRCNAME operator/_Pipeline_VITIS_LOOP_215_1 MODELNAME operator_Pipeline_VITIS_LOOP_215_1 RTLNAME ban_interface_operator_Pipeline_VITIS_LOOP_215_1}
  {SRCNAME _mul_Pipeline_VITIS_LOOP_169_1 MODELNAME p_mul_Pipeline_VITIS_LOOP_169_1 RTLNAME ban_interface_p_mul_Pipeline_VITIS_LOOP_169_1
    SUBMODULES {
      {MODELNAME ban_interface_fadd_32ns_32ns_32_4_full_dsp_1 RTLNAME ban_interface_fadd_32ns_32ns_32_4_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME ban_interface_fmul_32ns_32ns_32_3_max_dsp_1 RTLNAME ban_interface_fmul_32ns_32ns_32_3_max_dsp_1 BINDTYPE op TYPE fmul IMPL maxdsp LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME ban_interface_mux_32_32_1_1 RTLNAME ban_interface_mux_32_32_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME _mul_Pipeline_VITIS_LOOP_187_1 MODELNAME p_mul_Pipeline_VITIS_LOOP_187_1 RTLNAME ban_interface_p_mul_Pipeline_VITIS_LOOP_187_1}
  {SRCNAME _mul MODELNAME p_mul RTLNAME ban_interface_p_mul
    SUBMODULES {
      {MODELNAME ban_interface_p_mul_aux_RAM_AUTO_1R1W RTLNAME ban_interface_p_mul_aux_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME operator/_Pipeline_VITIS_LOOP_84_1 MODELNAME operator_Pipeline_VITIS_LOOP_84_1 RTLNAME ban_interface_operator_Pipeline_VITIS_LOOP_84_1}
  {SRCNAME operator/_Pipeline_VITIS_LOOP_92_2 MODELNAME operator_Pipeline_VITIS_LOOP_92_2 RTLNAME ban_interface_operator_Pipeline_VITIS_LOOP_92_2}
  {SRCNAME operator/_Pipeline_VITIS_LOOP_104_3 MODELNAME operator_Pipeline_VITIS_LOOP_104_3 RTLNAME ban_interface_operator_Pipeline_VITIS_LOOP_104_3}
  {SRCNAME operator/ MODELNAME operator_div RTLNAME ban_interface_operator_div
    SUBMODULES {
      {MODELNAME ban_interface_fdiv_32ns_32ns_32_9_no_dsp_1 RTLNAME ban_interface_fdiv_32ns_32ns_32_9_no_dsp_1 BINDTYPE op TYPE fdiv IMPL fabric LATENCY 8 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_84_111 MODELNAME ban_interface_Pipeline_VITIS_LOOP_84_111 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_84_111}
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_92_212 MODELNAME ban_interface_Pipeline_VITIS_LOOP_92_212 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_92_212}
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_104_313 MODELNAME ban_interface_Pipeline_VITIS_LOOP_104_313 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_104_313}
  {SRCNAME operator+_Pipeline_VITIS_LOOP_84_1 MODELNAME operator_Pipeline_VITIS_LOOP_84_1_s RTLNAME ban_interface_operator_Pipeline_VITIS_LOOP_84_1_s}
  {SRCNAME operator+_Pipeline_VITIS_LOOP_92_2 MODELNAME operator_Pipeline_VITIS_LOOP_92_2_s RTLNAME ban_interface_operator_Pipeline_VITIS_LOOP_92_2_s}
  {SRCNAME operator+_Pipeline_VITIS_LOOP_104_3 MODELNAME operator_Pipeline_VITIS_LOOP_104_3_s RTLNAME ban_interface_operator_Pipeline_VITIS_LOOP_104_3_s}
  {SRCNAME operator+_Pipeline_VITIS_LOOP_506_1 MODELNAME operator_Pipeline_VITIS_LOOP_506_1 RTLNAME ban_interface_operator_Pipeline_VITIS_LOOP_506_1}
  {SRCNAME operator+_Pipeline_VITIS_LOOP_21_1 MODELNAME operator_Pipeline_VITIS_LOOP_21_1 RTLNAME ban_interface_operator_Pipeline_VITIS_LOOP_21_1}
  {SRCNAME operator+ MODELNAME operator_add RTLNAME ban_interface_operator_add}
  {SRCNAME operator+.2_Pipeline_VITIS_LOOP_84_1 MODELNAME operator_2_Pipeline_VITIS_LOOP_84_1 RTLNAME ban_interface_operator_2_Pipeline_VITIS_LOOP_84_1}
  {SRCNAME operator+.2_Pipeline_VITIS_LOOP_92_2 MODELNAME operator_2_Pipeline_VITIS_LOOP_92_2 RTLNAME ban_interface_operator_2_Pipeline_VITIS_LOOP_92_2}
  {SRCNAME operator+.2_Pipeline_VITIS_LOOP_104_3 MODELNAME operator_2_Pipeline_VITIS_LOOP_104_3 RTLNAME ban_interface_operator_2_Pipeline_VITIS_LOOP_104_3}
  {SRCNAME operator+.2_Pipeline_VITIS_LOOP_506_1 MODELNAME operator_2_Pipeline_VITIS_LOOP_506_1 RTLNAME ban_interface_operator_2_Pipeline_VITIS_LOOP_506_1}
  {SRCNAME operator+.2_Pipeline_VITIS_LOOP_21_1 MODELNAME operator_2_Pipeline_VITIS_LOOP_21_1 RTLNAME ban_interface_operator_2_Pipeline_VITIS_LOOP_21_1}
  {SRCNAME operator+.2 MODELNAME operator_2 RTLNAME ban_interface_operator_2}
  {SRCNAME operator/.2_Pipeline_VITIS_LOOP_84_1 MODELNAME operator_2_Pipeline_VITIS_LOOP_84_1_s RTLNAME ban_interface_operator_2_Pipeline_VITIS_LOOP_84_1_s}
  {SRCNAME operator/.2_Pipeline_VITIS_LOOP_92_2 MODELNAME operator_2_Pipeline_VITIS_LOOP_92_2_s RTLNAME ban_interface_operator_2_Pipeline_VITIS_LOOP_92_2_s}
  {SRCNAME operator/.2_Pipeline_VITIS_LOOP_104_3 MODELNAME operator_2_Pipeline_VITIS_LOOP_104_3_s RTLNAME ban_interface_operator_2_Pipeline_VITIS_LOOP_104_3_s}
  {SRCNAME operator/.2 MODELNAME operator_2_s RTLNAME ban_interface_operator_2_s}
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_84_18 MODELNAME ban_interface_Pipeline_VITIS_LOOP_84_18 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_84_18}
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_92_29 MODELNAME ban_interface_Pipeline_VITIS_LOOP_92_29 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_92_29}
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_104_310 MODELNAME ban_interface_Pipeline_VITIS_LOOP_104_310 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_104_310}
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_84_1 MODELNAME ban_interface_Pipeline_VITIS_LOOP_84_1 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_84_1}
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_92_2 MODELNAME ban_interface_Pipeline_VITIS_LOOP_92_2 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_92_2}
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_104_3 MODELNAME ban_interface_Pipeline_VITIS_LOOP_104_3 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_104_3}
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_335_17 MODELNAME ban_interface_Pipeline_VITIS_LOOP_335_17 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_335_17}
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_335_16 MODELNAME ban_interface_Pipeline_VITIS_LOOP_335_16 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_335_16}
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_335_15 MODELNAME ban_interface_Pipeline_VITIS_LOOP_335_15 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_335_15}
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_335_1 MODELNAME ban_interface_Pipeline_VITIS_LOOP_335_1 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_335_1}
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_53_14 MODELNAME ban_interface_Pipeline_VITIS_LOOP_53_14 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_53_14}
  {SRCNAME ban_interface_Pipeline_VITIS_LOOP_53_1 MODELNAME ban_interface_Pipeline_VITIS_LOOP_53_1 RTLNAME ban_interface_ban_interface_Pipeline_VITIS_LOOP_53_1}
  {SRCNAME sqrt_Pipeline_VITIS_LOOP_68_1 MODELNAME sqrt_Pipeline_VITIS_LOOP_68_1 RTLNAME ban_interface_sqrt_Pipeline_VITIS_LOOP_68_1}
  {SRCNAME sqrt_Pipeline_VITIS_LOOP_444_1 MODELNAME sqrt_Pipeline_VITIS_LOOP_444_1 RTLNAME ban_interface_sqrt_Pipeline_VITIS_LOOP_444_1}
  {SRCNAME sqrt_Pipeline_VITIS_LOOP_169_1 MODELNAME sqrt_Pipeline_VITIS_LOOP_169_1 RTLNAME ban_interface_sqrt_Pipeline_VITIS_LOOP_169_1}
  {SRCNAME sqrt_Pipeline_VITIS_LOOP_187_1 MODELNAME sqrt_Pipeline_VITIS_LOOP_187_1 RTLNAME ban_interface_sqrt_Pipeline_VITIS_LOOP_187_1}
  {SRCNAME sqrt_Pipeline_VITIS_LOOP_21_1 MODELNAME sqrt_Pipeline_VITIS_LOOP_21_1 RTLNAME ban_interface_sqrt_Pipeline_VITIS_LOOP_21_1}
  {SRCNAME sqrt MODELNAME sqrt RTLNAME ban_interface_sqrt
    SUBMODULES {
      {MODELNAME ban_interface_fsqrt_32ns_32ns_32_8_no_dsp_1 RTLNAME ban_interface_fsqrt_32ns_32ns_32_8_no_dsp_1 BINDTYPE op TYPE fsqrt IMPL fabric LATENCY 7 ALLOW_PRAGMA 1}
      {MODELNAME ban_interface_sqrt_aux_RAM_AUTO_1R1W RTLNAME ban_interface_sqrt_aux_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME operator/.1_Pipeline_VITIS_LOOP_215_1 MODELNAME operator_1_Pipeline_VITIS_LOOP_215_1 RTLNAME ban_interface_operator_1_Pipeline_VITIS_LOOP_215_1}
  {SRCNAME _mul.1_Pipeline_VITIS_LOOP_169_1 MODELNAME p_mul_1_Pipeline_VITIS_LOOP_169_1 RTLNAME ban_interface_p_mul_1_Pipeline_VITIS_LOOP_169_1}
  {SRCNAME _mul.1_Pipeline_VITIS_LOOP_187_1 MODELNAME p_mul_1_Pipeline_VITIS_LOOP_187_1 RTLNAME ban_interface_p_mul_1_Pipeline_VITIS_LOOP_187_1}
  {SRCNAME _mul.1 MODELNAME p_mul_1 RTLNAME ban_interface_p_mul_1
    SUBMODULES {
      {MODELNAME ban_interface_p_mul_1_aux_RAM_AUTO_1R1W RTLNAME ban_interface_p_mul_1_aux_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME operator/.1_Pipeline_VITIS_LOOP_84_1 MODELNAME operator_1_Pipeline_VITIS_LOOP_84_1 RTLNAME ban_interface_operator_1_Pipeline_VITIS_LOOP_84_1}
  {SRCNAME operator/.1_Pipeline_VITIS_LOOP_92_2 MODELNAME operator_1_Pipeline_VITIS_LOOP_92_2 RTLNAME ban_interface_operator_1_Pipeline_VITIS_LOOP_92_2}
  {SRCNAME operator/.1_Pipeline_VITIS_LOOP_104_3 MODELNAME operator_1_Pipeline_VITIS_LOOP_104_3 RTLNAME ban_interface_operator_1_Pipeline_VITIS_LOOP_104_3}
  {SRCNAME operator/.1 MODELNAME operator_1 RTLNAME ban_interface_operator_1}
  {SRCNAME mul_body_Pipeline_VITIS_LOOP_169_1 MODELNAME mul_body_Pipeline_VITIS_LOOP_169_1 RTLNAME ban_interface_mul_body_Pipeline_VITIS_LOOP_169_1}
  {SRCNAME mul_body_Pipeline_VITIS_LOOP_187_1 MODELNAME mul_body_Pipeline_VITIS_LOOP_187_1 RTLNAME ban_interface_mul_body_Pipeline_VITIS_LOOP_187_1}
  {SRCNAME mul_body_Pipeline_VITIS_LOOP_21_1 MODELNAME mul_body_Pipeline_VITIS_LOOP_21_1 RTLNAME ban_interface_mul_body_Pipeline_VITIS_LOOP_21_1}
  {SRCNAME mul_body_Pipeline_VITIS_LOOP_84_1 MODELNAME mul_body_Pipeline_VITIS_LOOP_84_1 RTLNAME ban_interface_mul_body_Pipeline_VITIS_LOOP_84_1}
  {SRCNAME mul_body_Pipeline_VITIS_LOOP_92_2 MODELNAME mul_body_Pipeline_VITIS_LOOP_92_2 RTLNAME ban_interface_mul_body_Pipeline_VITIS_LOOP_92_2}
  {SRCNAME mul_body_Pipeline_VITIS_LOOP_104_3 MODELNAME mul_body_Pipeline_VITIS_LOOP_104_3 RTLNAME ban_interface_mul_body_Pipeline_VITIS_LOOP_104_3}
  {SRCNAME mul_body MODELNAME mul_body RTLNAME ban_interface_mul_body
    SUBMODULES {
      {MODELNAME ban_interface_mul_body_aux_RAM_AUTO_1R1W RTLNAME ban_interface_mul_body_aux_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME _sum.1_Pipeline_VITIS_LOOP_84_1 MODELNAME p_sum_1_Pipeline_VITIS_LOOP_84_1 RTLNAME ban_interface_p_sum_1_Pipeline_VITIS_LOOP_84_1}
  {SRCNAME _sum.1_Pipeline_VITIS_LOOP_92_2 MODELNAME p_sum_1_Pipeline_VITIS_LOOP_92_2 RTLNAME ban_interface_p_sum_1_Pipeline_VITIS_LOOP_92_2}
  {SRCNAME _sum.1_Pipeline_VITIS_LOOP_104_3 MODELNAME p_sum_1_Pipeline_VITIS_LOOP_104_3 RTLNAME ban_interface_p_sum_1_Pipeline_VITIS_LOOP_104_3}
  {SRCNAME _sum.1 MODELNAME p_sum_1 RTLNAME ban_interface_p_sum_1}
  {SRCNAME operator+.3_Pipeline_VITIS_LOOP_84_1 MODELNAME operator_3_Pipeline_VITIS_LOOP_84_1 RTLNAME ban_interface_operator_3_Pipeline_VITIS_LOOP_84_1}
  {SRCNAME operator+.3_Pipeline_VITIS_LOOP_92_2 MODELNAME operator_3_Pipeline_VITIS_LOOP_92_2 RTLNAME ban_interface_operator_3_Pipeline_VITIS_LOOP_92_2}
  {SRCNAME operator+.3_Pipeline_VITIS_LOOP_104_3 MODELNAME operator_3_Pipeline_VITIS_LOOP_104_3 RTLNAME ban_interface_operator_3_Pipeline_VITIS_LOOP_104_3}
  {SRCNAME operator+.3 MODELNAME operator_3 RTLNAME ban_interface_operator_3}
  {SRCNAME _sum_Pipeline_VITIS_LOOP_84_1 MODELNAME p_sum_Pipeline_VITIS_LOOP_84_1 RTLNAME ban_interface_p_sum_Pipeline_VITIS_LOOP_84_1}
  {SRCNAME _sum_Pipeline_VITIS_LOOP_92_2 MODELNAME p_sum_Pipeline_VITIS_LOOP_92_2 RTLNAME ban_interface_p_sum_Pipeline_VITIS_LOOP_92_2}
  {SRCNAME _sum_Pipeline_VITIS_LOOP_104_3 MODELNAME p_sum_Pipeline_VITIS_LOOP_104_3 RTLNAME ban_interface_p_sum_Pipeline_VITIS_LOOP_104_3}
  {SRCNAME _sum MODELNAME p_sum RTLNAME ban_interface_p_sum}
  {SRCNAME operator+.1 MODELNAME operator_1_s RTLNAME ban_interface_operator_1_s}
  {SRCNAME ban_interface MODELNAME ban_interface RTLNAME ban_interface IS_TOP 1
    SUBMODULES {
      {MODELNAME ban_interface_fcmp_32ns_32ns_1_2_no_dsp_1 RTLNAME ban_interface_fcmp_32ns_32ns_1_2_no_dsp_1 BINDTYPE op TYPE fcmp IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
    }
  }
}
