// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module main_operator_1_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        this_1_address0,
        this_1_ce0,
        this_1_we0,
        this_1_d0,
        this_1_q0,
        this_1_address1,
        this_1_ce1,
        this_1_we1,
        this_1_d1,
        this_1_q1,
        this_1_offset,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        ap_return,
        grp_fu_1967_p_din0,
        grp_fu_1967_p_din1,
        grp_fu_1967_p_opcode,
        grp_fu_1967_p_dout0,
        grp_fu_1967_p_ce,
        grp_fu_1934_p_din0,
        grp_fu_1934_p_din1,
        grp_fu_1934_p_opcode,
        grp_fu_1934_p_dout0,
        grp_fu_1934_p_ce,
        grp_fu_1960_p_din0,
        grp_fu_1960_p_din1,
        grp_fu_1960_p_opcode,
        grp_fu_1960_p_dout0,
        grp_fu_1960_p_ce
);

parameter    ap_ST_fsm_state1 = 28'd1;
parameter    ap_ST_fsm_state2 = 28'd2;
parameter    ap_ST_fsm_state3 = 28'd4;
parameter    ap_ST_fsm_state4 = 28'd8;
parameter    ap_ST_fsm_state5 = 28'd16;
parameter    ap_ST_fsm_state6 = 28'd32;
parameter    ap_ST_fsm_state7 = 28'd64;
parameter    ap_ST_fsm_state8 = 28'd128;
parameter    ap_ST_fsm_state9 = 28'd256;
parameter    ap_ST_fsm_state10 = 28'd512;
parameter    ap_ST_fsm_state11 = 28'd1024;
parameter    ap_ST_fsm_state12 = 28'd2048;
parameter    ap_ST_fsm_state13 = 28'd4096;
parameter    ap_ST_fsm_state14 = 28'd8192;
parameter    ap_ST_fsm_state15 = 28'd16384;
parameter    ap_ST_fsm_state16 = 28'd32768;
parameter    ap_ST_fsm_state17 = 28'd65536;
parameter    ap_ST_fsm_state18 = 28'd131072;
parameter    ap_ST_fsm_state19 = 28'd262144;
parameter    ap_ST_fsm_state20 = 28'd524288;
parameter    ap_ST_fsm_state21 = 28'd1048576;
parameter    ap_ST_fsm_state22 = 28'd2097152;
parameter    ap_ST_fsm_state23 = 28'd4194304;
parameter    ap_ST_fsm_state24 = 28'd8388608;
parameter    ap_ST_fsm_state25 = 28'd16777216;
parameter    ap_ST_fsm_state26 = 28'd33554432;
parameter    ap_ST_fsm_state27 = 28'd67108864;
parameter    ap_ST_fsm_state28 = 28'd134217728;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] p_read;
output  [5:0] this_1_address0;
output   this_1_ce0;
output   this_1_we0;
output  [31:0] this_1_d0;
input  [31:0] this_1_q0;
output  [5:0] this_1_address1;
output   this_1_ce1;
output   this_1_we1;
output  [31:0] this_1_d1;
input  [31:0] this_1_q1;
input  [4:0] this_1_offset;
input  [31:0] p_read1;
input  [31:0] p_read2;
input  [31:0] p_read3;
input  [31:0] p_read4;
output  [31:0] ap_return;
output  [31:0] grp_fu_1967_p_din0;
output  [31:0] grp_fu_1967_p_din1;
output  [4:0] grp_fu_1967_p_opcode;
input  [0:0] grp_fu_1967_p_dout0;
output   grp_fu_1967_p_ce;
output  [31:0] grp_fu_1934_p_din0;
output  [31:0] grp_fu_1934_p_din1;
output  [0:0] grp_fu_1934_p_opcode;
input  [31:0] grp_fu_1934_p_dout0;
output   grp_fu_1934_p_ce;
output  [31:0] grp_fu_1960_p_din0;
output  [31:0] grp_fu_1960_p_din1;
output  [4:0] grp_fu_1960_p_opcode;
input  [0:0] grp_fu_1960_p_dout0;
output   grp_fu_1960_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[5:0] this_1_address0;
reg this_1_ce0;
reg this_1_we0;
reg[31:0] this_1_d0;
reg[5:0] this_1_address1;
reg this_1_ce1;
reg this_1_we1;
reg[31:0] this_1_d1;
reg[31:0] ap_return;

(* fsm_encoding = "none" *) reg   [27:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] reg_362;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state20;
reg   [1:0] reg_369;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state12;
wire   [5:0] sub_ln60_fu_389_p2;
reg   [5:0] sub_ln60_reg_896;
reg   [5:0] this_1_addr_reg_906;
reg   [5:0] this_1_addr_1_reg_912;
reg   [5:0] this_1_addr_2_reg_918;
wire   [0:0] icmp_ln60_fu_422_p2;
reg   [0:0] icmp_ln60_reg_924;
wire   [0:0] icmp_ln60_4_fu_446_p2;
reg   [0:0] icmp_ln60_4_reg_928;
wire   [0:0] icmp_ln60_5_fu_452_p2;
reg   [0:0] icmp_ln60_5_reg_933;
wire   [0:0] and_ln60_fu_462_p2;
reg   [0:0] and_ln60_reg_938;
wire    ap_CS_fsm_state3;
wire   [0:0] and_ln60_2_fu_514_p2;
reg   [0:0] and_ln60_2_reg_942;
wire    ap_CS_fsm_state4;
wire   [1:0] trunc_ln295_fu_524_p1;
reg   [1:0] trunc_ln295_reg_946;
wire   [0:0] icmp_ln298_fu_528_p2;
reg   [0:0] icmp_ln298_reg_953;
wire   [0:0] icmp_ln301_fu_534_p2;
reg   [0:0] icmp_ln301_reg_957;
wire   [0:0] tmp_16_fu_540_p3;
reg   [0:0] tmp_16_reg_961;
reg   [5:0] this_1_addr_4_reg_992;
wire   [31:0] tmp_22_fu_582_p5;
reg   [31:0] tmp_22_reg_1001;
reg   [31:0] tmp_reg_1006;
wire    ap_CS_fsm_state10;
wire   [1:0] grp_fu_356_p2;
reg   [1:0] add_ln309_reg_1019;
wire   [1:0] sub11_fu_605_p2;
reg   [1:0] sub11_reg_1031;
wire   [0:0] grp_fu_350_p2;
reg   [5:0] this_1_addr_5_reg_1036;
wire    ap_CS_fsm_state14;
wire   [0:0] icmp_ln314_fu_663_p2;
reg   [0:0] icmp_ln314_reg_1044;
wire   [0:0] icmp_ln313_fu_651_p2;
wire   [31:0] tmp_23_fu_668_p5;
reg   [31:0] tmp_23_reg_1049;
wire   [1:0] add_ln317_fu_677_p2;
reg   [1:0] add_ln317_reg_1055;
wire   [0:0] icmp_ln330_fu_687_p2;
reg   [0:0] icmp_ln330_reg_1060;
wire   [31:0] tmp_24_fu_700_p5;
wire    ap_CS_fsm_state15;
wire   [31:0] select_ln314_fu_712_p3;
reg   [31:0] select_ln314_reg_1069;
wire    ap_CS_fsm_state18;
wire   [0:0] icmp_ln75_fu_736_p2;
reg   [0:0] icmp_ln75_reg_1074;
wire   [0:0] icmp_ln75_2_fu_742_p2;
reg   [0:0] icmp_ln75_2_reg_1079;
wire   [0:0] and_ln75_fu_752_p2;
reg   [0:0] and_ln75_reg_1084;
wire    ap_CS_fsm_state21;
wire   [1:0] empty_26_fu_761_p1;
reg   [1:0] empty_26_reg_1088;
wire    ap_CS_fsm_state23;
wire   [0:0] icmp_ln90_fu_766_p2;
reg   [0:0] icmp_ln90_reg_1094;
wire   [1:0] xor_ln90_fu_772_p2;
reg   [1:0] xor_ln90_reg_1098;
wire   [1:0] base_fu_784_p2;
wire    ap_CS_fsm_state24;
wire   [31:0] tmp_17_fu_800_p2;
wire   [0:0] icmp_ln102_fu_806_p2;
reg   [0:0] icmp_ln102_reg_1114;
wire   [2:0] select_ln102_fu_828_p3;
reg   [2:0] select_ln102_reg_1118;
wire    ap_CS_fsm_state25;
wire    grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_ap_start;
wire    grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_ap_done;
wire    grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_ap_idle;
wire    grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_ap_ready;
wire   [5:0] grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_this_1_address0;
wire    grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_this_1_ce0;
wire   [31:0] grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_idx_tmp_out;
wire    grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_idx_tmp_out_ap_vld;
wire   [31:0] grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_grp_fu_1123_p_din0;
wire   [31:0] grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_grp_fu_1123_p_din1;
wire   [4:0] grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_grp_fu_1123_p_opcode;
wire    grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_grp_fu_1123_p_ce;
wire    grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_ap_start;
wire    grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_ap_done;
wire    grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_ap_idle;
wire    grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_ap_ready;
wire   [5:0] grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_this_1_address0;
wire    grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_this_1_ce0;
wire    grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_this_1_we0;
wire   [31:0] grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_this_1_d0;
wire   [5:0] grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_this_1_address1;
wire    grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_this_1_ce1;
wire    grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_ap_start;
wire    grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_ap_done;
wire    grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_ap_idle;
wire    grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_ap_ready;
wire   [5:0] grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_this_1_address0;
wire    grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_this_1_ce0;
wire    grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_this_1_we0;
wire   [31:0] grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_this_1_d0;
reg   [0:0] ap_phi_mux_write_flag_0_phi_fu_212_p4;
reg   [0:0] write_flag_0_reg_208;
reg   [31:0] empty_25_reg_221;
reg   [1:0] base_0_lcssa_i3235_reg_231;
reg    ap_block_state24_on_subcall_done;
reg   [31:0] this_01_1_reg_243;
reg   [0:0] ap_phi_mux_write_flag_5_phi_fu_259_p16;
reg   [0:0] write_flag_5_reg_254;
wire    ap_CS_fsm_state27;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state26;
reg    ap_predicate_op205_call_state26;
reg    ap_block_state26_on_subcall_done;
reg   [31:0] ap_phi_mux_this_01_5_phi_fu_289_p16;
reg   [31:0] this_01_5_reg_285;
reg    grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_ap_start_reg;
wire    ap_CS_fsm_state22;
reg    grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_ap_start_reg;
reg    grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_ap_start_reg;
wire   [63:0] zext_ln60_2_fu_395_p1;
wire   [63:0] zext_ln288_fu_406_p1;
wire   [63:0] zext_ln288_1_fu_417_p1;
wire   [63:0] zext_ln325_1_fu_567_p1;
wire   [63:0] zext_ln310_1_fu_600_p1;
wire   [63:0] zext_ln317_1_fu_646_p1;
reg   [1:0] i_fu_98;
wire    ap_CS_fsm_state13;
reg   [31:0] num_aux_2_fu_102;
reg   [31:0] num_aux_2_1_fu_106;
reg   [31:0] num_aux_2_2_fu_110;
reg   [1:0] i_2_fu_114;
wire   [1:0] add_ln313_fu_657_p2;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state19;
reg   [31:0] grp_fu_337_p0;
reg   [31:0] grp_fu_337_p1;
wire    ap_CS_fsm_state7;
reg   [31:0] grp_fu_341_p0;
wire   [3:0] trunc_ln60_fu_377_p1;
wire   [5:0] tmp_21_cast_fu_381_p3;
wire   [5:0] zext_ln60_fu_373_p1;
wire   [5:0] add_ln288_fu_400_p2;
wire   [5:0] add_ln288_1_fu_411_p2;
wire   [31:0] bitcast_ln60_fu_428_p1;
wire   [7:0] tmp_s_fu_432_p4;
wire   [22:0] trunc_ln60_2_fu_442_p1;
wire   [0:0] or_ln60_fu_458_p2;
wire   [31:0] bitcast_ln60_1_fu_473_p1;
wire   [7:0] tmp_20_fu_476_p4;
wire   [22:0] trunc_ln60_3_fu_486_p1;
wire   [0:0] icmp_ln60_7_fu_496_p2;
wire   [0:0] icmp_ln60_6_fu_490_p2;
wire   [0:0] or_ln60_1_fu_502_p2;
wire   [0:0] and_ln60_1_fu_508_p2;
wire   [0:0] icmp_ln60_3_fu_468_p2;
wire   [31:0] i_8_fu_520_p2;
wire   [5:0] zext_ln325_fu_558_p1;
wire   [5:0] add_ln325_fu_562_p2;
wire   [1:0] tmp_22_fu_582_p4;
wire   [5:0] zext_ln310_fu_591_p1;
wire   [5:0] add_ln310_fu_595_p2;
wire   [5:0] zext_ln317_fu_637_p1;
wire   [5:0] add_ln317_1_fu_641_p2;
wire   [31:0] bitcast_ln75_fu_718_p1;
wire   [7:0] tmp_25_fu_722_p4;
wire   [22:0] trunc_ln75_fu_732_p1;
wire   [0:0] or_ln75_fu_748_p2;
wire   [1:0] sub_ln90_fu_779_p2;
wire   [1:0] xor_ln98_fu_790_p2;
wire  signed [31:0] sext_ln98_fu_796_p1;
wire   [2:0] zext_ln102_fu_812_p1;
wire   [0:0] icmp_ln102_2_fu_816_p2;
wire   [2:0] add_ln102_fu_822_p2;
wire   [31:0] this_p_write_assign_fu_837_p3;
reg    grp_fu_1123_ce;
reg   [31:0] ap_return_preg;
reg   [27:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
reg    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
reg    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
reg    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 28'd1;
#0 grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_ap_start_reg = 1'b0;
#0 grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_ap_start_reg = 1'b0;
#0 grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_ap_start_reg = 1'b0;
#0 ap_return_preg = 32'd0;
end

main_operator_1_Pipeline_VITIS_LOOP_82_1 grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_ap_start),
    .ap_done(grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_ap_done),
    .ap_idle(grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_ap_idle),
    .ap_ready(grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_ap_ready),
    .sub_ln60(sub_ln60_reg_896),
    .this_1_address0(grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_this_1_address0),
    .this_1_ce0(grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_this_1_ce0),
    .this_1_q0(this_1_q0),
    .idx_tmp_out(grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_idx_tmp_out),
    .idx_tmp_out_ap_vld(grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_idx_tmp_out_ap_vld),
    .grp_fu_1123_p_din0(grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_grp_fu_1123_p_din0),
    .grp_fu_1123_p_din1(grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_grp_fu_1123_p_din1),
    .grp_fu_1123_p_opcode(grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_grp_fu_1123_p_opcode),
    .grp_fu_1123_p_dout0(grp_fu_1967_p_dout0),
    .grp_fu_1123_p_ce(grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_grp_fu_1123_p_ce)
);

main_operator_1_Pipeline_VITIS_LOOP_90_2 grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_ap_start),
    .ap_done(grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_ap_done),
    .ap_idle(grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_ap_idle),
    .ap_ready(grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_ap_ready),
    .zext_ln90(empty_26_reg_1088),
    .xor_ln90(xor_ln90_reg_1098),
    .sub_ln60(sub_ln60_reg_896),
    .this_1_address0(grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_this_1_address0),
    .this_1_ce0(grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_this_1_ce0),
    .this_1_we0(grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_this_1_we0),
    .this_1_d0(grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_this_1_d0),
    .this_1_address1(grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_this_1_address1),
    .this_1_ce1(grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_this_1_ce1),
    .this_1_q1(this_1_q1)
);

main_operator_1_Pipeline_VITIS_LOOP_102_3 grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_ap_start),
    .ap_done(grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_ap_done),
    .ap_idle(grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_ap_idle),
    .ap_ready(grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_ap_ready),
    .zext_ln102(base_0_lcssa_i3235_reg_231),
    .sub_ln60(sub_ln60_reg_896),
    .this_1_address0(grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_this_1_address0),
    .this_1_ce0(grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_this_1_ce0),
    .this_1_we0(grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_this_1_we0),
    .this_1_d0(grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_this_1_d0),
    .zext_ln102_4(select_ln102_reg_1118)
);

main_mux_32_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_32_32_1_1_U315(
    .din0(p_read2),
    .din1(p_read3),
    .din2(p_read4),
    .din3(tmp_22_fu_582_p4),
    .dout(tmp_22_fu_582_p5)
);

main_mux_32_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_32_32_1_1_U316(
    .din0(p_read2),
    .din1(p_read3),
    .din2(p_read4),
    .din3(i_2_fu_114),
    .dout(tmp_23_fu_668_p5)
);

main_mux_32_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_32_32_1_1_U317(
    .din0(num_aux_2_fu_102),
    .din1(num_aux_2_1_fu_106),
    .din2(num_aux_2_2_fu_110),
    .din3(add_ln317_reg_1055),
    .dout(tmp_24_fu_700_p5)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 32'd0;
    end else begin
        if (((1'b0 == ap_block_state26_on_subcall_done) & (1'b1 == ap_CS_fsm_state26))) begin
            ap_return_preg <= this_p_write_assign_fu_837_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state25)) begin
            grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_ap_start_reg <= 1'b1;
        end else if ((grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_ap_ready == 1'b1)) begin
            grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state21) & (1'd1 == and_ln75_fu_752_p2))) begin
            grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_ap_start_reg <= 1'b1;
        end else if ((grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_ap_ready == 1'b1)) begin
            grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln90_fu_766_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state23))) begin
            grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_ap_start_reg <= 1'b1;
        end else if ((grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_ap_ready == 1'b1)) begin
            grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state24_on_subcall_done) & (icmp_ln102_fu_806_p2 == 1'd0) & (icmp_ln90_reg_1094 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        base_0_lcssa_i3235_reg_231 <= base_fu_784_p2;
    end else if (((icmp_ln90_fu_766_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state23))) begin
        base_0_lcssa_i3235_reg_231 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & (icmp_ln313_fu_651_p2 == 1'd1) & (tmp_16_reg_961 == 1'd1))) begin
        empty_25_reg_221 <= p_read1;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_fu_350_p2 == 1'd1))) begin
        empty_25_reg_221 <= p_read;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (grp_fu_350_p2 == 1'd1))) begin
        i_2_fu_114 <= 2'd0;
    end else if (((1'b1 == ap_CS_fsm_state14) & (icmp_ln313_fu_651_p2 == 1'd0) & (tmp_16_reg_961 == 1'd1))) begin
        i_2_fu_114 <= add_ln313_fu_657_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (tmp_16_fu_540_p3 == 1'd1) & (icmp_ln301_fu_534_p2 == 1'd0) & (icmp_ln298_fu_528_p2 == 1'd0) & (1'd0 == and_ln60_2_fu_514_p2))) begin
        i_fu_98 <= 2'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (tmp_16_fu_540_p3 == 1'd0) & (icmp_ln301_fu_534_p2 == 1'd0) & (icmp_ln298_fu_528_p2 == 1'd0) & (1'd0 == and_ln60_2_fu_514_p2))) begin
        i_fu_98 <= trunc_ln295_fu_524_p1;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_fu_350_p2 == 1'd0))) begin
        i_fu_98 <= grp_fu_356_p2;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        i_fu_98 <= add_ln309_reg_1019;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        reg_362 <= this_1_q1;
    end else if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state2))) begin
        reg_362 <= this_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state24_on_subcall_done) & (icmp_ln102_fu_806_p2 == 1'd0) & (icmp_ln90_reg_1094 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        this_01_1_reg_243 <= tmp_17_fu_800_p2;
    end else if (((icmp_ln90_fu_766_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state23))) begin
        this_01_1_reg_243 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state24_on_subcall_done) & (icmp_ln102_fu_806_p2 == 1'd1) & (icmp_ln90_reg_1094 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        this_01_5_reg_285 <= tmp_17_fu_800_p2;
    end else if (((1'b0 == ap_block_state26_on_subcall_done) & (1'b1 == ap_CS_fsm_state26) & (((((icmp_ln90_reg_1094 == 1'd0) & (icmp_ln330_reg_1060 == 1'd1) & (icmp_ln301_reg_957 == 1'd0) & (icmp_ln298_reg_953 == 1'd0) & (1'd0 == and_ln60_2_reg_942) & (1'd0 == and_ln60_reg_938) & (1'd1 == and_ln75_reg_1084)) | ((icmp_ln102_reg_1114 == 1'd0) & (icmp_ln330_reg_1060 == 1'd1) & (icmp_ln301_reg_957 == 1'd0) & (icmp_ln298_reg_953 == 1'd0) & (1'd0 == and_ln60_2_reg_942) & (1'd0 == and_ln60_reg_938) & (1'd1 == and_ln75_reg_1084))) | ((icmp_ln102_reg_1114 == 1'd0) & (icmp_ln330_reg_1060 == 1'd1) & (icmp_ln301_reg_957 == 1'd0) & (icmp_ln298_reg_953 == 1'd0) & (1'd0 == and_ln60_2_reg_942) & (1'd1 == and_ln75_reg_1084) & (icmp_ln60_reg_924 == 1'd0))) | ((icmp_ln90_reg_1094 == 1'd0) & (icmp_ln330_reg_1060 == 1'd1) & (icmp_ln301_reg_957 == 1'd0) & (icmp_ln298_reg_953 == 1'd0) & (1'd0 == and_ln60_2_reg_942) & (1'd1 == and_ln75_reg_1084) & (icmp_ln60_reg_924 == 1'd0))))) begin
        this_01_5_reg_285 <= this_01_1_reg_243;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | ((1'b1 == ap_CS_fsm_state21) & (1'd0 == and_ln75_fu_752_p2)) | ((1'b1 == ap_CS_fsm_state14) & (((icmp_ln330_fu_687_p2 == 1'd0) & (tmp_16_reg_961 == 1'd0)) | ((icmp_ln330_fu_687_p2 == 1'd0) & (icmp_ln313_fu_651_p2 == 1'd1)))))) begin
        this_01_5_reg_285 <= p_read1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & (icmp_ln313_fu_651_p2 == 1'd1) & (tmp_16_reg_961 == 1'd1))) begin
        write_flag_0_reg_208 <= 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state5) & (grp_fu_350_p2 == 1'd1))) begin
        write_flag_0_reg_208 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state21) & (1'd0 == and_ln75_fu_752_p2))) begin
        write_flag_5_reg_254 <= write_flag_0_reg_208;
    end else if (((1'b1 == ap_CS_fsm_state14) & (((icmp_ln330_fu_687_p2 == 1'd0) & (tmp_16_reg_961 == 1'd0)) | ((icmp_ln330_fu_687_p2 == 1'd0) & (icmp_ln313_fu_651_p2 == 1'd1))))) begin
        write_flag_5_reg_254 <= ap_phi_mux_write_flag_0_phi_fu_212_p4;
    end else if ((((1'b1 == ap_CS_fsm_state4) & (icmp_ln298_fu_528_p2 == 1'd1) & (1'd0 == and_ln60_2_fu_514_p2)) | ((1'b1 == ap_CS_fsm_state4) & (1'd1 == and_ln60_2_fu_514_p2)))) begin
        write_flag_5_reg_254 <= 1'd0;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | ((1'b0 == ap_block_state26_on_subcall_done) & (1'b1 == ap_CS_fsm_state26) & (((((icmp_ln90_reg_1094 == 1'd0) & (icmp_ln330_reg_1060 == 1'd1) & (icmp_ln301_reg_957 == 1'd0) & (icmp_ln298_reg_953 == 1'd0) & (1'd0 == and_ln60_2_reg_942) & (1'd0 == and_ln60_reg_938) & (1'd1 == and_ln75_reg_1084)) | ((icmp_ln102_reg_1114 == 1'd0) & (icmp_ln330_reg_1060 == 1'd1) & (icmp_ln301_reg_957 == 1'd0) & (icmp_ln298_reg_953 == 1'd0) & (1'd0 == and_ln60_2_reg_942) & (1'd0 == and_ln60_reg_938) & (1'd1 == and_ln75_reg_1084))) | ((icmp_ln102_reg_1114 == 1'd0) & (icmp_ln330_reg_1060 == 1'd1) & (icmp_ln301_reg_957 == 1'd0) & (icmp_ln298_reg_953 == 1'd0) & (1'd0 == and_ln60_2_reg_942) & (1'd1 == and_ln75_reg_1084) & (icmp_ln60_reg_924 == 1'd0))) | ((icmp_ln90_reg_1094 == 1'd0) & (icmp_ln330_reg_1060 == 1'd1) & (icmp_ln301_reg_957 == 1'd0) & (icmp_ln298_reg_953 == 1'd0) & (1'd0 == and_ln60_2_reg_942) & (1'd1 == and_ln75_reg_1084) & (icmp_ln60_reg_924 == 1'd0)))) | ((1'b0 == ap_block_state24_on_subcall_done) & (icmp_ln102_fu_806_p2 == 1'd1) & (icmp_ln90_reg_1094 == 1'd1) & (1'b1 == ap_CS_fsm_state24)))) begin
        write_flag_5_reg_254 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        add_ln309_reg_1019 <= grp_fu_356_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & (icmp_ln313_fu_651_p2 == 1'd0) & (tmp_16_reg_961 == 1'd1))) begin
        add_ln317_reg_1055 <= add_ln317_fu_677_p2;
        icmp_ln314_reg_1044 <= icmp_ln314_fu_663_p2;
        tmp_23_reg_1049 <= tmp_23_fu_668_p5;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        and_ln60_2_reg_942 <= and_ln60_2_fu_514_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln60_reg_924 == 1'd1))) begin
        and_ln60_reg_938 <= and_ln60_fu_462_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        and_ln75_reg_1084 <= and_ln75_fu_752_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        empty_26_reg_1088 <= empty_26_fu_761_p1;
        icmp_ln90_reg_1094 <= icmp_ln90_fu_766_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln90_reg_1094 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        icmp_ln102_reg_1114 <= icmp_ln102_fu_806_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'd0 == and_ln60_2_fu_514_p2))) begin
        icmp_ln298_reg_953 <= icmp_ln298_fu_528_p2;
        trunc_ln295_reg_946 <= trunc_ln295_fu_524_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln298_fu_528_p2 == 1'd0) & (1'd0 == and_ln60_2_fu_514_p2))) begin
        icmp_ln301_reg_957 <= icmp_ln301_fu_534_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & ((icmp_ln313_fu_651_p2 == 1'd1) | (tmp_16_reg_961 == 1'd0)))) begin
        icmp_ln330_reg_1060 <= icmp_ln330_fu_687_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_ln60_4_reg_928 <= icmp_ln60_4_fu_446_p2;
        icmp_ln60_5_reg_933 <= icmp_ln60_5_fu_452_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln60_reg_924 <= icmp_ln60_fu_422_p2;
        sub_ln60_reg_896 <= sub_ln60_fu_389_p2;
        this_1_addr_1_reg_912 <= zext_ln288_fu_406_p1;
        this_1_addr_2_reg_918 <= zext_ln288_1_fu_417_p1;
        this_1_addr_reg_906 <= zext_ln60_2_fu_395_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        icmp_ln75_2_reg_1079 <= icmp_ln75_2_fu_742_p2;
        icmp_ln75_reg_1074 <= icmp_ln75_fu_736_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((reg_369 == 2'd1) & (1'b1 == ap_CS_fsm_state13))) begin
        num_aux_2_1_fu_106 <= this_1_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(reg_369 == 2'd1) & ~(reg_369 == 2'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        num_aux_2_2_fu_110 <= this_1_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((reg_369 == 2'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        num_aux_2_fu_102 <= this_1_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state5))) begin
        reg_369 <= i_fu_98;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        select_ln102_reg_1118 <= select_ln102_fu_828_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        select_ln314_reg_1069 <= select_ln314_fu_712_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (grp_fu_350_p2 == 1'd1))) begin
        sub11_reg_1031 <= sub11_fu_605_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        this_1_addr_4_reg_992 <= zext_ln325_1_fu_567_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & (tmp_16_reg_961 == 1'd1))) begin
        this_1_addr_5_reg_1036 <= zext_ln317_1_fu_646_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln301_fu_534_p2 == 1'd0) & (icmp_ln298_fu_528_p2 == 1'd0) & (1'd0 == and_ln60_2_fu_514_p2))) begin
        tmp_16_reg_961 <= i_8_fu_520_p2[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_22_reg_1001 <= tmp_22_fu_582_p5;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        tmp_reg_1006 <= grp_fu_1934_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln90_fu_766_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state23))) begin
        xor_ln90_reg_1098 <= xor_ln90_fu_772_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

always @ (*) begin
    if ((grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_ap_done == 1'b0)) begin
        ap_ST_fsm_state22_blk = 1'b1;
    end else begin
        ap_ST_fsm_state22_blk = 1'b0;
    end
end

assign ap_ST_fsm_state23_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state24_on_subcall_done)) begin
        ap_ST_fsm_state24_blk = 1'b1;
    end else begin
        ap_ST_fsm_state24_blk = 1'b0;
    end
end

assign ap_ST_fsm_state25_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state26_on_subcall_done)) begin
        ap_ST_fsm_state26_blk = 1'b1;
    end else begin
        ap_ST_fsm_state26_blk = 1'b0;
    end
end

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((1'b0 == ap_block_state26_on_subcall_done) & (1'b1 == ap_CS_fsm_state26)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) & (((((icmp_ln90_reg_1094 == 1'd0) & (icmp_ln330_reg_1060 == 1'd1) & (icmp_ln301_reg_957 == 1'd0) & (icmp_ln298_reg_953 == 1'd0) & (1'd0 == and_ln60_2_reg_942) & (1'd0 == and_ln60_reg_938) & (1'd1 == and_ln75_reg_1084)) | ((icmp_ln102_reg_1114 == 1'd0) & (icmp_ln330_reg_1060 == 1'd1) & (icmp_ln301_reg_957 == 1'd0) & (icmp_ln298_reg_953 == 1'd0) & (1'd0 == and_ln60_2_reg_942) & (1'd0 == and_ln60_reg_938) & (1'd1 == and_ln75_reg_1084))) | ((icmp_ln102_reg_1114 == 1'd0) & (icmp_ln330_reg_1060 == 1'd1) & (icmp_ln301_reg_957 == 1'd0) & (icmp_ln298_reg_953 == 1'd0) & (1'd0 == and_ln60_2_reg_942) & (1'd1 == and_ln75_reg_1084) & (icmp_ln60_reg_924 == 1'd0))) | ((icmp_ln90_reg_1094 == 1'd0) & (icmp_ln330_reg_1060 == 1'd1) & (icmp_ln301_reg_957 == 1'd0) & (icmp_ln298_reg_953 == 1'd0) & (1'd0 == and_ln60_2_reg_942) & (1'd1 == and_ln75_reg_1084) & (icmp_ln60_reg_924 == 1'd0))))) begin
        ap_phi_mux_this_01_5_phi_fu_289_p16 = this_01_1_reg_243;
    end else begin
        ap_phi_mux_this_01_5_phi_fu_289_p16 = this_01_5_reg_285;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (icmp_ln313_fu_651_p2 == 1'd1) & (tmp_16_reg_961 == 1'd1))) begin
        ap_phi_mux_write_flag_0_phi_fu_212_p4 = 1'd1;
    end else begin
        ap_phi_mux_write_flag_0_phi_fu_212_p4 = write_flag_0_reg_208;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) & (((((icmp_ln90_reg_1094 == 1'd0) & (icmp_ln330_reg_1060 == 1'd1) & (icmp_ln301_reg_957 == 1'd0) & (icmp_ln298_reg_953 == 1'd0) & (1'd0 == and_ln60_2_reg_942) & (1'd0 == and_ln60_reg_938) & (1'd1 == and_ln75_reg_1084)) | ((icmp_ln102_reg_1114 == 1'd0) & (icmp_ln330_reg_1060 == 1'd1) & (icmp_ln301_reg_957 == 1'd0) & (icmp_ln298_reg_953 == 1'd0) & (1'd0 == and_ln60_2_reg_942) & (1'd0 == and_ln60_reg_938) & (1'd1 == and_ln75_reg_1084))) | ((icmp_ln102_reg_1114 == 1'd0) & (icmp_ln330_reg_1060 == 1'd1) & (icmp_ln301_reg_957 == 1'd0) & (icmp_ln298_reg_953 == 1'd0) & (1'd0 == and_ln60_2_reg_942) & (1'd1 == and_ln75_reg_1084) & (icmp_ln60_reg_924 == 1'd0))) | ((icmp_ln90_reg_1094 == 1'd0) & (icmp_ln330_reg_1060 == 1'd1) & (icmp_ln301_reg_957 == 1'd0) & (icmp_ln298_reg_953 == 1'd0) & (1'd0 == and_ln60_2_reg_942) & (1'd1 == and_ln75_reg_1084) & (icmp_ln60_reg_924 == 1'd0))))) begin
        ap_phi_mux_write_flag_5_phi_fu_259_p16 = 1'd1;
    end else begin
        ap_phi_mux_write_flag_5_phi_fu_259_p16 = write_flag_5_reg_254;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state26_on_subcall_done) & (1'b1 == ap_CS_fsm_state26))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state26_on_subcall_done) & (1'b1 == ap_CS_fsm_state26))) begin
        ap_return = this_p_write_assign_fu_837_p3;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_fu_1123_ce = grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_grp_fu_1123_p_ce;
    end else begin
        grp_fu_1123_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_337_p0 = tmp_23_reg_1049;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_337_p0 = reg_362;
    end else begin
        grp_fu_337_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_337_p1 = tmp_24_fu_700_p5;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_337_p1 = tmp_22_reg_1001;
    end else begin
        grp_fu_337_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_341_p0 = p_read2;
    end else if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state2))) begin
        grp_fu_341_p0 = this_1_q0;
    end else begin
        grp_fu_341_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        this_1_address0 = this_1_addr_2_reg_918;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        this_1_address0 = this_1_addr_4_reg_992;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state4))) begin
        this_1_address0 = this_1_addr_reg_906;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        this_1_address0 = this_1_addr_1_reg_912;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        this_1_address0 = zext_ln60_2_fu_395_p1;
    end else if (((ap_predicate_op205_call_state26 == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
        this_1_address0 = grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_this_1_address0;
    end else if (((icmp_ln90_reg_1094 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        this_1_address0 = grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_this_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        this_1_address0 = grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_this_1_address0;
    end else begin
        this_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        this_1_address1 = this_1_addr_2_reg_918;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        this_1_address1 = this_1_addr_5_reg_1036;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        this_1_address1 = zext_ln310_1_fu_600_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        this_1_address1 = zext_ln325_1_fu_567_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        this_1_address1 = this_1_addr_1_reg_912;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        this_1_address1 = this_1_addr_reg_906;
    end else if (((icmp_ln90_reg_1094 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        this_1_address1 = grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_this_1_address1;
    end else begin
        this_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        this_1_ce0 = 1'b1;
    end else if (((ap_predicate_op205_call_state26 == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
        this_1_ce0 = grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_this_1_ce0;
    end else if (((icmp_ln90_reg_1094 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        this_1_ce0 = grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_this_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        this_1_ce0 = grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_this_1_ce0;
    end else begin
        this_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        this_1_ce1 = 1'b1;
    end else if (((icmp_ln90_reg_1094 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        this_1_ce1 = grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_this_1_ce1;
    end else begin
        this_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        this_1_d0 = p_read4;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        this_1_d0 = tmp_reg_1006;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        this_1_d0 = p_read2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        this_1_d0 = p_read3;
    end else if (((ap_predicate_op205_call_state26 == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
        this_1_d0 = grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_this_1_d0;
    end else if (((icmp_ln90_reg_1094 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        this_1_d0 = grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_this_1_d0;
    end else begin
        this_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        this_1_d1 = p_read4;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        this_1_d1 = select_ln314_reg_1069;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        this_1_d1 = p_read3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        this_1_d1 = p_read2;
    end else begin
        this_1_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state27) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln301_fu_534_p2 == 1'd1) & (icmp_ln298_fu_528_p2 == 1'd0) & (1'd0 == and_ln60_2_fu_514_p2)) | ((1'b1 == ap_CS_fsm_state3) & (1'd1 == and_ln60_fu_462_p2) & (icmp_ln60_reg_924 == 1'd1)))) begin
        this_1_we0 = 1'b1;
    end else if (((ap_predicate_op205_call_state26 == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
        this_1_we0 = grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_this_1_we0;
    end else if (((icmp_ln90_reg_1094 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        this_1_we0 = grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_this_1_we0;
    end else begin
        this_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state28) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln301_fu_534_p2 == 1'd1) & (icmp_ln298_fu_528_p2 == 1'd0) & (1'd0 == and_ln60_2_fu_514_p2)) | ((1'b1 == ap_CS_fsm_state3) & (1'd1 == and_ln60_fu_462_p2) & (icmp_ln60_reg_924 == 1'd1)))) begin
        this_1_we1 = 1'b1;
    end else begin
        this_1_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln60_fu_422_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln60_fu_422_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (1'd1 == and_ln60_fu_462_p2) & (icmp_ln60_reg_924 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (tmp_16_fu_540_p3 == 1'd1) & (icmp_ln301_fu_534_p2 == 1'd0) & (icmp_ln298_fu_528_p2 == 1'd0) & (1'd0 == and_ln60_2_fu_514_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else if (((1'b1 == ap_CS_fsm_state4) & (tmp_16_fu_540_p3 == 1'd0) & (icmp_ln301_fu_534_p2 == 1'd0) & (icmp_ln298_fu_528_p2 == 1'd0) & (1'd0 == and_ln60_2_fu_514_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln301_fu_534_p2 == 1'd1) & (icmp_ln298_fu_528_p2 == 1'd0) & (1'd0 == and_ln60_2_fu_514_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_fu_350_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (grp_fu_350_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state14 : begin
            if (((1'b1 == ap_CS_fsm_state14) & (((icmp_ln330_fu_687_p2 == 1'd0) & (tmp_16_reg_961 == 1'd0)) | ((icmp_ln330_fu_687_p2 == 1'd0) & (icmp_ln313_fu_651_p2 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else if (((1'b1 == ap_CS_fsm_state14) & (((icmp_ln330_fu_687_p2 == 1'd1) & (tmp_16_reg_961 == 1'd0)) | ((icmp_ln330_fu_687_p2 == 1'd1) & (icmp_ln313_fu_651_p2 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            if (((1'b1 == ap_CS_fsm_state21) & (1'd0 == and_ln75_fu_752_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state22 : begin
            if (((grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            if (((1'b0 == ap_block_state24_on_subcall_done) & (icmp_ln102_fu_806_p2 == 1'd1) & (icmp_ln90_reg_1094 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else if (((1'b0 == ap_block_state24_on_subcall_done) & (1'b1 == ap_CS_fsm_state24) & ((icmp_ln102_fu_806_p2 == 1'd0) | (icmp_ln90_reg_1094 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            if (((1'b0 == ap_block_state26_on_subcall_done) & (1'b1 == ap_CS_fsm_state26))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln102_fu_822_p2 = (zext_ln102_fu_812_p1 + 3'd1);

assign add_ln288_1_fu_411_p2 = (sub_ln60_fu_389_p2 + 6'd2);

assign add_ln288_fu_400_p2 = (sub_ln60_fu_389_p2 + 6'd1);

assign add_ln310_fu_595_p2 = (sub_ln60_reg_896 + zext_ln310_fu_591_p1);

assign add_ln313_fu_657_p2 = (i_2_fu_114 + 2'd1);

assign add_ln317_1_fu_641_p2 = (sub_ln60_reg_896 + zext_ln317_fu_637_p1);

assign add_ln317_fu_677_p2 = (i_2_fu_114 + trunc_ln295_reg_946);

assign add_ln325_fu_562_p2 = (sub_ln60_reg_896 + zext_ln325_fu_558_p1);

assign and_ln60_1_fu_508_p2 = (or_ln60_1_fu_502_p2 & grp_fu_1960_p_dout0);

assign and_ln60_2_fu_514_p2 = (icmp_ln60_3_fu_468_p2 & and_ln60_1_fu_508_p2);

assign and_ln60_fu_462_p2 = (or_ln60_fu_458_p2 & grp_fu_1960_p_dout0);

assign and_ln75_fu_752_p2 = (or_ln75_fu_748_p2 & grp_fu_1960_p_dout0);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state24_on_subcall_done = ((grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_ap_done == 1'b0) & (icmp_ln90_reg_1094 == 1'd1));
end

always @ (*) begin
    ap_block_state26_on_subcall_done = ((ap_predicate_op205_call_state26 == 1'b1) & (grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_ap_done == 1'b0));
end

always @ (*) begin
    ap_predicate_op205_call_state26 = (((((icmp_ln90_reg_1094 == 1'd0) & (icmp_ln330_reg_1060 == 1'd1) & (icmp_ln301_reg_957 == 1'd0) & (icmp_ln298_reg_953 == 1'd0) & (1'd0 == and_ln60_2_reg_942) & (1'd0 == and_ln60_reg_938) & (1'd1 == and_ln75_reg_1084)) | ((icmp_ln102_reg_1114 == 1'd0) & (icmp_ln330_reg_1060 == 1'd1) & (icmp_ln301_reg_957 == 1'd0) & (icmp_ln298_reg_953 == 1'd0) & (1'd0 == and_ln60_2_reg_942) & (1'd0 == and_ln60_reg_938) & (1'd1 == and_ln75_reg_1084))) | ((icmp_ln102_reg_1114 == 1'd0) & (icmp_ln330_reg_1060 == 1'd1) & (icmp_ln301_reg_957 == 1'd0) & (icmp_ln298_reg_953 == 1'd0) & (1'd0 == and_ln60_2_reg_942) & (1'd1 == and_ln75_reg_1084) & (icmp_ln60_reg_924 == 1'd0))) | ((icmp_ln90_reg_1094 == 1'd0) & (icmp_ln330_reg_1060 == 1'd1) & (icmp_ln301_reg_957 == 1'd0) & (icmp_ln298_reg_953 == 1'd0) & (1'd0 == and_ln60_2_reg_942) & (1'd1 == and_ln75_reg_1084) & (icmp_ln60_reg_924 == 1'd0)));
end

assign base_fu_784_p2 = (sub_ln90_fu_779_p2 + 2'd1);

assign bitcast_ln60_1_fu_473_p1 = p_read2;

assign bitcast_ln60_fu_428_p1 = this_1_q0;

assign bitcast_ln75_fu_718_p1 = this_1_q0;

assign empty_26_fu_761_p1 = grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_idx_tmp_out[1:0];

assign grp_fu_1934_p_ce = 1'b1;

assign grp_fu_1934_p_din0 = grp_fu_337_p0;

assign grp_fu_1934_p_din1 = grp_fu_337_p1;

assign grp_fu_1934_p_opcode = 2'd0;

assign grp_fu_1960_p_ce = 1'b1;

assign grp_fu_1960_p_din0 = grp_fu_341_p0;

assign grp_fu_1960_p_din1 = 32'd0;

assign grp_fu_1960_p_opcode = 5'd1;

assign grp_fu_1967_p_ce = grp_fu_1123_ce;

assign grp_fu_1967_p_din0 = grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_grp_fu_1123_p_din0;

assign grp_fu_1967_p_din1 = grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_grp_fu_1123_p_din1;

assign grp_fu_1967_p_opcode = grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_grp_fu_1123_p_opcode;

assign grp_fu_350_p2 = ((i_fu_98 == 2'd3) ? 1'b1 : 1'b0);

assign grp_fu_356_p2 = (i_fu_98 + 2'd1);

assign grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_ap_start = grp_operator_1_Pipeline_VITIS_LOOP_102_3_fu_327_ap_start_reg;

assign grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_ap_start = grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_ap_start_reg;

assign grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_ap_start = grp_operator_1_Pipeline_VITIS_LOOP_90_2_fu_318_ap_start_reg;

assign i_8_fu_520_p2 = (p_read - p_read1);

assign icmp_ln102_2_fu_816_p2 = ((base_0_lcssa_i3235_reg_231 != 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln102_fu_806_p2 = ((base_fu_784_p2 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln298_fu_528_p2 = (($signed(i_8_fu_520_p2) > $signed(32'd2)) ? 1'b1 : 1'b0);

assign icmp_ln301_fu_534_p2 = (($signed(i_8_fu_520_p2) < $signed(32'd4294967294)) ? 1'b1 : 1'b0);

assign icmp_ln313_fu_651_p2 = ((i_2_fu_114 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln314_fu_663_p2 = ((i_2_fu_114 < sub11_reg_1031) ? 1'b1 : 1'b0);

assign icmp_ln330_fu_687_p2 = ((p_read == p_read1) ? 1'b1 : 1'b0);

assign icmp_ln60_3_fu_468_p2 = ((p_read1 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln60_4_fu_446_p2 = ((tmp_s_fu_432_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln60_5_fu_452_p2 = ((trunc_ln60_2_fu_442_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln60_6_fu_490_p2 = ((tmp_20_fu_476_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln60_7_fu_496_p2 = ((trunc_ln60_3_fu_486_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln60_fu_422_p2 = ((p_read == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln75_2_fu_742_p2 = ((trunc_ln75_fu_732_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln75_fu_736_p2 = ((tmp_25_fu_722_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln90_fu_766_p2 = ((grp_operator_1_Pipeline_VITIS_LOOP_82_1_fu_310_idx_tmp_out < 32'd3) ? 1'b1 : 1'b0);

assign or_ln60_1_fu_502_p2 = (icmp_ln60_7_fu_496_p2 | icmp_ln60_6_fu_490_p2);

assign or_ln60_fu_458_p2 = (icmp_ln60_5_reg_933 | icmp_ln60_4_reg_928);

assign or_ln75_fu_748_p2 = (icmp_ln75_reg_1074 | icmp_ln75_2_reg_1079);

assign select_ln102_fu_828_p3 = ((icmp_ln102_2_fu_816_p2[0:0] == 1'b1) ? 3'd3 : add_ln102_fu_822_p2);

assign select_ln314_fu_712_p3 = ((icmp_ln314_reg_1044[0:0] == 1'b1) ? tmp_23_reg_1049 : grp_fu_1934_p_dout0);

assign sext_ln98_fu_796_p1 = $signed(xor_ln98_fu_790_p2);

assign sub11_fu_605_p2 = (2'd0 - trunc_ln295_reg_946);

assign sub_ln60_fu_389_p2 = (tmp_21_cast_fu_381_p3 - zext_ln60_fu_373_p1);

assign sub_ln90_fu_779_p2 = ($signed(2'd2) - $signed(empty_26_reg_1088));

assign this_p_write_assign_fu_837_p3 = ((ap_phi_mux_write_flag_5_phi_fu_259_p16[0:0] == 1'b1) ? ap_phi_mux_this_01_5_phi_fu_289_p16 : p_read);

assign tmp_16_fu_540_p3 = i_8_fu_520_p2[32'd31];

assign tmp_17_fu_800_p2 = ($signed(sext_ln98_fu_796_p1) + $signed(empty_25_reg_221));

assign tmp_20_fu_476_p4 = {{bitcast_ln60_1_fu_473_p1[30:23]}};

assign tmp_21_cast_fu_381_p3 = {{trunc_ln60_fu_377_p1}, {2'd0}};

assign tmp_22_fu_582_p4 = (reg_369 - trunc_ln295_reg_946);

assign tmp_25_fu_722_p4 = {{bitcast_ln75_fu_718_p1[30:23]}};

assign tmp_s_fu_432_p4 = {{bitcast_ln60_fu_428_p1[30:23]}};

assign trunc_ln295_fu_524_p1 = i_8_fu_520_p2[1:0];

assign trunc_ln60_2_fu_442_p1 = bitcast_ln60_fu_428_p1[22:0];

assign trunc_ln60_3_fu_486_p1 = bitcast_ln60_1_fu_473_p1[22:0];

assign trunc_ln60_fu_377_p1 = this_1_offset[3:0];

assign trunc_ln75_fu_732_p1 = bitcast_ln75_fu_718_p1[22:0];

assign xor_ln90_fu_772_p2 = (empty_26_fu_761_p1 ^ 2'd3);

assign xor_ln98_fu_790_p2 = (sub_ln90_fu_779_p2 ^ 2'd2);

assign zext_ln102_fu_812_p1 = base_0_lcssa_i3235_reg_231;

assign zext_ln288_1_fu_417_p1 = add_ln288_1_fu_411_p2;

assign zext_ln288_fu_406_p1 = add_ln288_fu_400_p2;

assign zext_ln310_1_fu_600_p1 = add_ln310_fu_595_p2;

assign zext_ln310_fu_591_p1 = i_fu_98;

assign zext_ln317_1_fu_646_p1 = add_ln317_1_fu_641_p2;

assign zext_ln317_fu_637_p1 = i_2_fu_114;

assign zext_ln325_1_fu_567_p1 = add_ln325_fu_562_p2;

assign zext_ln325_fu_558_p1 = i_fu_98;

assign zext_ln60_2_fu_395_p1 = sub_ln60_fu_389_p2;

assign zext_ln60_fu_373_p1 = this_1_offset;

endmodule //main_operator_1_s
