include("../../Utils/GrossonePkg/src/Grossone.jl")
#include("../src/NSGAII.jl")
include("../src/NSGAII_GAA.jl")
#include("../test/MPL3.jl")
#MPL3("../outputs/provaMPL3.txt")
#include("../test/MPL4.jl")
#MPL4("../outputs/provaMPL4.txt")
#include("../test/MPL_GAA.jl")
#include("../test/MPL_GAA v2.jl")
#MPL_GAA("../outputs/provaMPL_GAA v2.txt")
include("../test/MPL_GAA v3.jl")
MPL_GAA("../outputs/provaMPL_GAA v3.txt")