// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ban_interface_operator_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read13,
        b_p_read,
        p_read4,
        p_read25,
        p_read3,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3
);

parameter    ap_ST_fsm_state1 = 25'd1;
parameter    ap_ST_fsm_state2 = 25'd2;
parameter    ap_ST_fsm_state3 = 25'd4;
parameter    ap_ST_fsm_state4 = 25'd8;
parameter    ap_ST_fsm_state5 = 25'd16;
parameter    ap_ST_fsm_state6 = 25'd32;
parameter    ap_ST_fsm_state7 = 25'd64;
parameter    ap_ST_fsm_state8 = 25'd128;
parameter    ap_ST_fsm_state9 = 25'd256;
parameter    ap_ST_fsm_state10 = 25'd512;
parameter    ap_ST_fsm_state11 = 25'd1024;
parameter    ap_ST_fsm_state12 = 25'd2048;
parameter    ap_ST_fsm_state13 = 25'd4096;
parameter    ap_ST_fsm_state14 = 25'd8192;
parameter    ap_ST_fsm_state15 = 25'd16384;
parameter    ap_ST_fsm_state16 = 25'd32768;
parameter    ap_ST_fsm_state17 = 25'd65536;
parameter    ap_ST_fsm_state18 = 25'd131072;
parameter    ap_ST_fsm_state19 = 25'd262144;
parameter    ap_ST_fsm_state20 = 25'd524288;
parameter    ap_ST_fsm_state21 = 25'd1048576;
parameter    ap_ST_fsm_state22 = 25'd2097152;
parameter    ap_ST_fsm_state23 = 25'd4194304;
parameter    ap_ST_fsm_state24 = 25'd8388608;
parameter    ap_ST_fsm_state25 = 25'd16777216;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [127:0] p_read13;
input  [31:0] b_p_read;
input  [31:0] p_read4;
input  [31:0] p_read25;
input  [31:0] p_read3;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;
output  [31:0] ap_return_3;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] ap_return_0;
reg[31:0] ap_return_1;
reg[31:0] ap_return_2;
reg[31:0] ap_return_3;

(* fsm_encoding = "none" *) reg   [24:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [95:0] trunc_ln129_fu_435_p1;
reg   [95:0] trunc_ln129_reg_1135;
wire   [31:0] c_p_fu_439_p1;
reg   [31:0] c_p_reg_1140;
wire   [0:0] icmp_ln61_fu_443_p2;
reg   [0:0] icmp_ln61_reg_1148;
wire   [31:0] bitcast_ln61_fu_449_p1;
wire   [0:0] and_ln61_fu_490_p2;
reg   [0:0] and_ln61_reg_1157;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln61_8_fu_496_p2;
reg   [0:0] icmp_ln61_8_reg_1161;
wire   [0:0] and_ln61_4_fu_536_p2;
reg   [0:0] and_ln61_4_reg_1165;
wire    ap_CS_fsm_state3;
wire   [31:0] diff_p_fu_542_p2;
reg   [31:0] diff_p_reg_1169;
wire   [1:0] trunc_ln138_fu_546_p1;
reg   [1:0] trunc_ln138_reg_1175;
wire   [0:0] icmp_ln141_fu_550_p2;
reg   [0:0] icmp_ln141_reg_1180;
wire   [0:0] icmp_ln144_fu_556_p2;
reg   [0:0] icmp_ln144_reg_1184;
wire   [0:0] tmp_fu_562_p3;
reg   [0:0] tmp_reg_1188;
wire   [1:0] diff_p_1_fu_570_p2;
reg   [1:0] diff_p_1_reg_1192;
wire   [0:0] icmp_ln77_fu_576_p2;
reg   [0:0] icmp_ln77_reg_1197;
wire   [0:0] trunc_ln117_fu_619_p1;
reg   [0:0] trunc_ln117_reg_1202;
wire    ap_CS_fsm_state5;
wire   [31:0] bitcast_ln117_fu_642_p1;
wire    ap_CS_fsm_state6;
wire   [0:0] tmp_52_fu_647_p3;
reg   [0:0] tmp_52_reg_1232;
wire    ap_CS_fsm_state9;
wire   [31:0] trunc_ln117_1_fu_744_p1;
reg   [31:0] trunc_ln117_1_reg_1236;
wire   [31:0] bitcast_ln117_1_fu_748_p1;
wire    ap_CS_fsm_state10;
wire   [31:0] grp_fu_395_p2;
wire    ap_CS_fsm_state13;
wire   [31:0] trunc_ln117_4_fu_836_p1;
reg   [31:0] trunc_ln117_4_reg_1251;
wire   [31:0] bitcast_ln117_2_fu_840_p1;
wire    ap_CS_fsm_state14;
reg   [31:0] tmp_55_reg_1261;
wire    ap_CS_fsm_state17;
wire   [0:0] and_ln77_1_fu_886_p2;
reg   [0:0] and_ln77_1_reg_1269;
wire   [1:0] empty_fu_894_p1;
reg   [1:0] empty_reg_1273;
wire    ap_CS_fsm_state19;
wire   [0:0] icmp_ln92_fu_899_p2;
reg   [0:0] icmp_ln92_reg_1279;
wire   [1:0] xor_ln92_fu_905_p2;
reg   [1:0] xor_ln92_reg_1283;
wire   [31:0] tmp_59_fu_946_p2;
wire    ap_CS_fsm_state21;
wire   [0:0] icmp_ln104_fu_951_p2;
reg   [0:0] icmp_ln104_reg_1303;
wire   [2:0] select_ln104_fu_973_p3;
reg   [2:0] select_ln104_reg_1307;
wire   [31:0] bitcast_ln142_fu_1018_p1;
wire    ap_CS_fsm_state24;
wire   [31:0] bitcast_ln142_1_fu_1022_p1;
wire   [31:0] bitcast_ln142_2_fu_1026_p1;
wire   [31:0] bitcast_ln136_fu_1030_p1;
wire    ap_CS_fsm_state25;
wire   [31:0] bitcast_ln136_1_fu_1034_p1;
wire   [31:0] bitcast_ln136_2_fu_1038_p1;
wire    grp_p_sum_1_fu_346_ap_start;
wire    grp_p_sum_1_fu_346_ap_done;
wire    grp_p_sum_1_fu_346_ap_idle;
wire    grp_p_sum_1_fu_346_ap_ready;
wire   [31:0] grp_p_sum_1_fu_346_ap_return_0;
wire   [31:0] grp_p_sum_1_fu_346_ap_return_1;
wire   [31:0] grp_p_sum_1_fu_346_ap_return_2;
wire   [31:0] grp_p_sum_1_fu_346_ap_return_3;
wire   [31:0] grp_p_sum_1_fu_346_grp_fu_395_p_din0;
wire   [31:0] grp_p_sum_1_fu_346_grp_fu_395_p_din1;
wire   [1:0] grp_p_sum_1_fu_346_grp_fu_395_p_opcode;
wire    grp_p_sum_1_fu_346_grp_fu_395_p_ce;
wire   [31:0] grp_p_sum_1_fu_346_grp_fu_1342_p_din0;
wire   [31:0] grp_p_sum_1_fu_346_grp_fu_1342_p_din1;
wire   [4:0] grp_p_sum_1_fu_346_grp_fu_1342_p_opcode;
wire    grp_p_sum_1_fu_346_grp_fu_1342_p_ce;
wire    grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_ap_start;
wire    grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_ap_done;
wire    grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_ap_idle;
wire    grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_ap_ready;
wire   [31:0] grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_idx_tmp_out;
wire    grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_idx_tmp_out_ap_vld;
wire   [31:0] grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_grp_fu_1342_p_din0;
wire   [31:0] grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_grp_fu_1342_p_din1;
wire   [4:0] grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_grp_fu_1342_p_opcode;
wire    grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_grp_fu_1342_p_ce;
wire    grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_ap_start;
wire    grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_ap_done;
wire    grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_ap_idle;
wire    grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_ap_ready;
wire   [31:0] grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_agg_result_1_1_out;
wire    grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_agg_result_1_1_out_ap_vld;
wire   [31:0] grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_agg_result_112_0_out;
wire    grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_agg_result_112_0_out_ap_vld;
wire   [31:0] grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_agg_result_12_0_out;
wire    grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_agg_result_12_0_out_ap_vld;
wire    grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_ap_start;
wire    grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_ap_done;
wire    grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_ap_idle;
wire    grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_ap_ready;
wire   [31:0] grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_agg_result_1_4_out;
wire    grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_agg_result_1_4_out_ap_vld;
wire   [31:0] grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_agg_result_112_3_out;
wire    grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_agg_result_112_3_out_ap_vld;
wire   [31:0] grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_agg_result_12_3_out;
wire    grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_agg_result_12_3_out_ap_vld;
reg   [31:0] agg_result_1_0_reg_184;
reg   [31:0] agg_result_112_5_reg_194;
reg   [31:0] agg_result_1_3_reg_204;
reg   [31:0] agg_result_112_2_reg_215;
reg   [31:0] agg_result_12_2_reg_226;
reg   [1:0] ap_phi_mux_base_0_lcssa_i_i1013_phi_fu_240_p4;
reg   [1:0] base_0_lcssa_i_i1013_reg_236;
wire   [1:0] base_fu_929_p2;
reg   [31:0] agg_result_01_0_reg_248;
reg   [31:0] ap_phi_mux_agg_result_1_6_phi_fu_262_p16;
reg   [31:0] agg_result_1_6_reg_259;
wire    ap_CS_fsm_state23;
reg   [31:0] ap_phi_mux_agg_result_112_6_phi_fu_284_p16;
reg   [31:0] agg_result_112_6_reg_281;
reg   [31:0] ap_phi_mux_agg_result_12_5_phi_fu_306_p16;
reg   [31:0] agg_result_12_5_reg_303;
reg   [31:0] ap_phi_mux_agg_result_01_4_phi_fu_327_p16;
reg   [31:0] agg_result_01_4_reg_324;
reg    grp_p_sum_1_fu_346_ap_start_reg;
wire    ap_CS_fsm_state4;
reg    grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_ap_start_reg;
wire    ap_CS_fsm_state18;
reg    grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_ap_start_reg;
wire    ap_CS_fsm_state20;
reg    grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_ap_start_reg;
wire    ap_CS_fsm_state22;
reg   [31:0] grp_fu_395_p0;
reg   [31:0] grp_fu_395_p1;
reg   [31:0] grp_fu_401_p0;
wire    ap_CS_fsm_state16;
wire   [31:0] grp_fu_407_p4;
wire   [7:0] tmp_s_fu_454_p4;
wire   [22:0] trunc_ln61_3_fu_463_p4;
wire   [0:0] icmp_ln61_10_fu_478_p2;
wire   [0:0] icmp_ln61_9_fu_472_p2;
wire   [0:0] or_ln61_fu_484_p2;
wire   [0:0] grp_fu_401_p2;
wire   [31:0] bitcast_ln61_1_fu_501_p1;
wire   [7:0] tmp_49_fu_504_p4;
wire   [22:0] trunc_ln61_1_fu_514_p1;
wire   [0:0] icmp_ln61_12_fu_524_p2;
wire   [0:0] icmp_ln61_11_fu_518_p2;
wire   [0:0] or_ln61_1_fu_530_p2;
wire   [36:0] shl_ln_fu_580_p3;
wire   [37:0] zext_ln117_fu_588_p1;
wire   [37:0] add_ln117_fu_592_p2;
wire   [127:0] zext_ln117_1_fu_598_p1;
wire   [127:0] shl_ln117_fu_602_p2;
wire   [127:0] and_ln117_fu_608_p2;
wire   [127:0] lshr_ln117_fu_613_p2;
wire   [31:0] zext_ln117_2_fu_639_p1;
wire   [31:0] add_ln117_1_fu_654_p2;
wire   [36:0] shl_ln117_2_fu_659_p3;
wire   [37:0] zext_ln117_4_fu_667_p1;
wire   [37:0] add_ln117_2_fu_671_p2;
wire   [37:0] add_ln117_3_fu_681_p2;
wire   [127:0] zext_ln117_5_fu_687_p1;
wire   [30:0] tmp_53_fu_697_p4;
wire   [0:0] icmp_ln117_fu_707_p2;
wire   [127:0] shl_ln117_1_fu_691_p2;
wire   [127:0] zext_ln117_3_fu_677_p1;
wire   [127:0] select_ln117_fu_713_p3;
wire   [127:0] shl_ln117_3_fu_721_p2;
wire   [127:0] sub_ln117_fu_727_p2;
wire   [127:0] and_ln117_1_fu_733_p2;
wire   [127:0] lshr_ln117_1_fu_738_p2;
wire   [0:0] trunc_ln117_2_fu_752_p1;
wire   [5:0] shl_ln117_5_fu_755_p3;
wire   [6:0] zext_ln117_7_fu_763_p1;
wire   [6:0] add_ln117_4_fu_767_p2;
wire   [6:0] or_ln_fu_781_p4;
wire   [96:0] zext_ln117_9_fu_791_p1;
wire   [96:0] shl_ln117_4_fu_795_p2;
wire   [64:0] zext_ln117_8_fu_777_p1;
wire   [64:0] shl_ln117_6_fu_805_p2;
wire   [95:0] trunc_ln117_3_fu_801_p1;
wire   [95:0] zext_ln117_10_fu_811_p1;
wire   [95:0] sub_ln117_1_fu_815_p2;
wire   [95:0] and_ln117_2_fu_821_p2;
wire   [127:0] zext_ln117_11_fu_826_p1;
wire   [127:0] zext_ln117_6_fu_773_p1;
wire   [127:0] lshr_ln117_2_fu_830_p2;
wire   [31:0] bitcast_ln77_fu_844_p1;
wire   [7:0] tmp_56_fu_848_p4;
wire   [22:0] trunc_ln77_fu_858_p1;
wire   [0:0] icmp_ln77_5_fu_868_p2;
wire   [0:0] icmp_ln77_4_fu_862_p2;
wire   [0:0] or_ln77_fu_874_p2;
wire   [0:0] and_ln77_fu_880_p2;
wire   [1:0] sub_ln92_fu_924_p2;
wire   [1:0] xor_ln100_fu_936_p2;
wire  signed [31:0] sext_ln100_fu_942_p1;
wire   [2:0] zext_ln104_fu_957_p1;
wire   [0:0] icmp_ln104_4_fu_961_p2;
wire   [2:0] add_ln104_fu_967_p2;
wire   [31:0] grp_fu_417_p4;
wire   [31:0] grp_fu_426_p4;
reg    grp_fu_395_ce;
wire   [0:0] grp_fu_1342_p2;
reg   [31:0] grp_fu_1342_p0;
reg   [31:0] grp_fu_1342_p1;
reg    grp_fu_1342_ce;
reg   [4:0] grp_fu_1342_opcode;
reg   [31:0] ap_return_0_preg;
reg   [31:0] ap_return_1_preg;
reg   [31:0] ap_return_2_preg;
reg   [31:0] ap_return_3_preg;
reg   [24:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
reg    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 25'd1;
#0 grp_p_sum_1_fu_346_ap_start_reg = 1'b0;
#0 grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_ap_start_reg = 1'b0;
#0 grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_ap_start_reg = 1'b0;
#0 grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_ap_start_reg = 1'b0;
#0 ap_return_0_preg = 32'd0;
#0 ap_return_1_preg = 32'd0;
#0 ap_return_2_preg = 32'd0;
#0 ap_return_3_preg = 32'd0;
end

ban_interface_p_sum_1 grp_p_sum_1_fu_346(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_p_sum_1_fu_346_ap_start),
    .ap_done(grp_p_sum_1_fu_346_ap_done),
    .ap_idle(grp_p_sum_1_fu_346_ap_idle),
    .ap_ready(grp_p_sum_1_fu_346_ap_ready),
    .p_read13(p_read13),
    .p_read4(p_read4),
    .p_read10(p_read25),
    .p_read11(p_read3),
    .diff_p(trunc_ln138_reg_1175),
    .ap_return_0(grp_p_sum_1_fu_346_ap_return_0),
    .ap_return_1(grp_p_sum_1_fu_346_ap_return_1),
    .ap_return_2(grp_p_sum_1_fu_346_ap_return_2),
    .ap_return_3(grp_p_sum_1_fu_346_ap_return_3),
    .grp_fu_395_p_din0(grp_p_sum_1_fu_346_grp_fu_395_p_din0),
    .grp_fu_395_p_din1(grp_p_sum_1_fu_346_grp_fu_395_p_din1),
    .grp_fu_395_p_opcode(grp_p_sum_1_fu_346_grp_fu_395_p_opcode),
    .grp_fu_395_p_dout0(grp_fu_395_p2),
    .grp_fu_395_p_ce(grp_p_sum_1_fu_346_grp_fu_395_p_ce),
    .grp_fu_1342_p_din0(grp_p_sum_1_fu_346_grp_fu_1342_p_din0),
    .grp_fu_1342_p_din1(grp_p_sum_1_fu_346_grp_fu_1342_p_din1),
    .grp_fu_1342_p_opcode(grp_p_sum_1_fu_346_grp_fu_1342_p_opcode),
    .grp_fu_1342_p_dout0(grp_fu_1342_p2),
    .grp_fu_1342_p_ce(grp_p_sum_1_fu_346_grp_fu_1342_p_ce)
);

ban_interface_operator_3_Pipeline_VITIS_LOOP_84_1 grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_ap_start),
    .ap_done(grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_ap_done),
    .ap_idle(grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_ap_idle),
    .ap_ready(grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_ap_ready),
    .agg_result_1_0(agg_result_1_0_reg_184),
    .agg_result_112_5(agg_result_112_5_reg_194),
    .tmp_69(tmp_55_reg_1261),
    .idx_tmp_out(grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_idx_tmp_out),
    .idx_tmp_out_ap_vld(grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_idx_tmp_out_ap_vld),
    .grp_fu_1342_p_din0(grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_grp_fu_1342_p_din0),
    .grp_fu_1342_p_din1(grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_grp_fu_1342_p_din1),
    .grp_fu_1342_p_opcode(grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_grp_fu_1342_p_opcode),
    .grp_fu_1342_p_dout0(grp_fu_1342_p2),
    .grp_fu_1342_p_ce(grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_grp_fu_1342_p_ce)
);

ban_interface_operator_3_Pipeline_VITIS_LOOP_92_2 grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_ap_start),
    .ap_done(grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_ap_done),
    .ap_idle(grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_ap_idle),
    .ap_ready(grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_ap_ready),
    .agg_result_1_0(agg_result_1_0_reg_184),
    .agg_result_112_5(agg_result_112_5_reg_194),
    .tmp_69(tmp_55_reg_1261),
    .zext_ln92(empty_reg_1273),
    .xor_ln92(xor_ln92_reg_1283),
    .agg_result_1_1_out(grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_agg_result_1_1_out),
    .agg_result_1_1_out_ap_vld(grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_agg_result_1_1_out_ap_vld),
    .agg_result_112_0_out(grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_agg_result_112_0_out),
    .agg_result_112_0_out_ap_vld(grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_agg_result_112_0_out_ap_vld),
    .agg_result_12_0_out(grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_agg_result_12_0_out),
    .agg_result_12_0_out_ap_vld(grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_agg_result_12_0_out_ap_vld)
);

ban_interface_operator_3_Pipeline_VITIS_LOOP_104_3 grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_ap_start),
    .ap_done(grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_ap_done),
    .ap_idle(grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_ap_idle),
    .ap_ready(grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_ap_ready),
    .agg_result_1_3(agg_result_1_3_reg_204),
    .agg_result_112_2(agg_result_112_2_reg_215),
    .agg_result_12_2(agg_result_12_2_reg_226),
    .zext_ln104(base_0_lcssa_i_i1013_reg_236),
    .zext_ln104_8(select_ln104_reg_1307),
    .agg_result_1_4_out(grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_agg_result_1_4_out),
    .agg_result_1_4_out_ap_vld(grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_agg_result_1_4_out_ap_vld),
    .agg_result_112_3_out(grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_agg_result_112_3_out),
    .agg_result_112_3_out_ap_vld(grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_agg_result_112_3_out_ap_vld),
    .agg_result_12_3_out(grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_agg_result_12_3_out),
    .agg_result_12_3_out_ap_vld(grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_agg_result_12_3_out_ap_vld)
);

ban_interface_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U551(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_395_p0),
    .din1(grp_fu_395_p1),
    .ce(grp_fu_395_ce),
    .dout(grp_fu_395_p2)
);

ban_interface_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U552(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_401_p0),
    .din1(32'd0),
    .ce(1'b1),
    .opcode(5'd1),
    .dout(grp_fu_401_p2)
);

ban_interface_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U553(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1342_p0),
    .din1(grp_fu_1342_p1),
    .ce(grp_fu_1342_ce),
    .opcode(grp_fu_1342_opcode),
    .dout(grp_fu_1342_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state23)) begin
            ap_return_0_preg <= ap_phi_mux_agg_result_01_4_phi_fu_327_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state23)) begin
            ap_return_1_preg <= ap_phi_mux_agg_result_1_6_phi_fu_262_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state23)) begin
            ap_return_2_preg <= ap_phi_mux_agg_result_112_6_phi_fu_284_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state23)) begin
            ap_return_3_preg <= ap_phi_mux_agg_result_12_5_phi_fu_306_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state21) & ((icmp_ln104_fu_951_p2 == 1'd0) | (icmp_ln92_reg_1279 == 1'd0)))) begin
            grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_ap_start_reg <= 1'b1;
        end else if ((grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_ap_ready == 1'b1)) begin
            grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_ap_start_reg <= 1'b0;
    end else begin
        if (((1'd1 == and_ln77_1_fu_886_p2) & (1'b1 == ap_CS_fsm_state17))) begin
            grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_ap_start_reg <= 1'b1;
        end else if ((grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_ap_ready == 1'b1)) begin
            grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln92_fu_899_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
            grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_ap_start_reg <= 1'b1;
        end else if ((grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_ap_ready == 1'b1)) begin
            grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_p_sum_1_fu_346_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_p_sum_1_fu_346_ap_start_reg <= 1'b1;
        end else if ((grp_p_sum_1_fu_346_ap_ready == 1'b1)) begin
            grp_p_sum_1_fu_346_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln104_fu_951_p2 == 1'd0) & (icmp_ln92_reg_1279 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        agg_result_01_0_reg_248 <= tmp_59_fu_946_p2;
    end else if (((icmp_ln92_fu_899_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        agg_result_01_0_reg_248 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln104_fu_951_p2 == 1'd1) & (icmp_ln92_reg_1279 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        agg_result_01_4_reg_324 <= tmp_59_fu_946_p2;
    end else if ((((1'b1 == ap_CS_fsm_state3) & (((icmp_ln61_8_reg_1161 == 1'd0) & (icmp_ln144_fu_556_p2 == 1'd1) & (icmp_ln141_fu_550_p2 == 1'd0)) | ((1'd0 == and_ln61_4_fu_536_p2) & (icmp_ln144_fu_556_p2 == 1'd1) & (icmp_ln141_fu_550_p2 == 1'd0)))) | ((1'd0 == and_ln77_1_fu_886_p2) & (1'b1 == ap_CS_fsm_state17)) | ((1'd1 == and_ln61_fu_490_p2) & (icmp_ln61_reg_1148 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        agg_result_01_4_reg_324 <= b_p_read;
    end else if (((1'b1 == ap_CS_fsm_state23) & (((((((((1'd0 == and_ln61_4_reg_1165) & (1'd0 == and_ln61_reg_1157) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0)) | ((1'd0 == and_ln61_4_reg_1165) & (1'd0 == and_ln61_reg_1157) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_reg_1157) & (icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_reg_1157) & (icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_4_reg_1165) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_4_reg_1165) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))))) begin
        agg_result_01_4_reg_324 <= agg_result_01_0_reg_248;
    end else if (((grp_p_sum_1_fu_346_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        agg_result_01_4_reg_324 <= grp_p_sum_1_fu_346_ap_return_0;
    end else if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24))) begin
        agg_result_01_4_reg_324 <= c_p_reg_1140;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln104_fu_951_p2 == 1'd0) & (icmp_ln92_reg_1279 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        agg_result_112_2_reg_215 <= grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_agg_result_112_0_out;
    end else if (((icmp_ln92_fu_899_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        agg_result_112_2_reg_215 <= agg_result_112_5_reg_194;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (tmp_52_fu_647_p3 == 1'd1))) begin
        agg_result_112_5_reg_194 <= p_read25;
    end else if (((1'b1 == ap_CS_fsm_state13) & (tmp_52_reg_1232 == 1'd0))) begin
        agg_result_112_5_reg_194 <= grp_fu_395_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln77_1_fu_886_p2) & (1'b1 == ap_CS_fsm_state17))) begin
        agg_result_112_6_reg_281 <= agg_result_112_5_reg_194;
    end else if (((icmp_ln104_fu_951_p2 == 1'd1) & (icmp_ln92_reg_1279 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        agg_result_112_6_reg_281 <= grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_agg_result_112_0_out;
    end else if ((((1'b1 == ap_CS_fsm_state3) & (((icmp_ln61_8_reg_1161 == 1'd0) & (icmp_ln144_fu_556_p2 == 1'd1) & (icmp_ln141_fu_550_p2 == 1'd0)) | ((1'd0 == and_ln61_4_fu_536_p2) & (icmp_ln144_fu_556_p2 == 1'd1) & (icmp_ln141_fu_550_p2 == 1'd0)))) | ((1'd1 == and_ln61_fu_490_p2) & (icmp_ln61_reg_1148 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        agg_result_112_6_reg_281 <= p_read25;
    end else if (((1'b1 == ap_CS_fsm_state23) & (((((((((1'd0 == and_ln61_4_reg_1165) & (1'd0 == and_ln61_reg_1157) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0)) | ((1'd0 == and_ln61_4_reg_1165) & (1'd0 == and_ln61_reg_1157) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_reg_1157) & (icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_reg_1157) & (icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_4_reg_1165) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_4_reg_1165) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))))) begin
        agg_result_112_6_reg_281 <= grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_agg_result_112_3_out;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        agg_result_112_6_reg_281 <= bitcast_ln136_1_fu_1034_p1;
    end else if (((grp_p_sum_1_fu_346_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        agg_result_112_6_reg_281 <= grp_p_sum_1_fu_346_ap_return_2;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        agg_result_112_6_reg_281 <= bitcast_ln142_1_fu_1022_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln104_fu_951_p2 == 1'd0) & (icmp_ln92_reg_1279 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        agg_result_12_2_reg_226 <= grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_agg_result_12_0_out;
    end else if (((icmp_ln92_fu_899_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        agg_result_12_2_reg_226 <= tmp_55_reg_1261;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln77_1_fu_886_p2) & (1'b1 == ap_CS_fsm_state17))) begin
        agg_result_12_5_reg_303 <= grp_fu_395_p2;
    end else if (((icmp_ln104_fu_951_p2 == 1'd1) & (icmp_ln92_reg_1279 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        agg_result_12_5_reg_303 <= grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_agg_result_12_0_out;
    end else if ((((1'b1 == ap_CS_fsm_state3) & (((icmp_ln61_8_reg_1161 == 1'd0) & (icmp_ln144_fu_556_p2 == 1'd1) & (icmp_ln141_fu_550_p2 == 1'd0)) | ((1'd0 == and_ln61_4_fu_536_p2) & (icmp_ln144_fu_556_p2 == 1'd1) & (icmp_ln141_fu_550_p2 == 1'd0)))) | ((1'd1 == and_ln61_fu_490_p2) & (icmp_ln61_reg_1148 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        agg_result_12_5_reg_303 <= p_read3;
    end else if (((1'b1 == ap_CS_fsm_state23) & (((((((((1'd0 == and_ln61_4_reg_1165) & (1'd0 == and_ln61_reg_1157) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0)) | ((1'd0 == and_ln61_4_reg_1165) & (1'd0 == and_ln61_reg_1157) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_reg_1157) & (icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_reg_1157) & (icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_4_reg_1165) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_4_reg_1165) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))))) begin
        agg_result_12_5_reg_303 <= grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_agg_result_12_3_out;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        agg_result_12_5_reg_303 <= bitcast_ln136_2_fu_1038_p1;
    end else if (((grp_p_sum_1_fu_346_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        agg_result_12_5_reg_303 <= grp_p_sum_1_fu_346_ap_return_3;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        agg_result_12_5_reg_303 <= bitcast_ln142_2_fu_1026_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (((icmp_ln61_8_reg_1161 == 1'd0) & (icmp_ln77_fu_576_p2 == 1'd0) & (tmp_fu_562_p3 == 1'd1) & (icmp_ln144_fu_556_p2 == 1'd0) & (icmp_ln141_fu_550_p2 == 1'd0)) | ((1'd0 == and_ln61_4_fu_536_p2) & (icmp_ln77_fu_576_p2 == 1'd0) & (tmp_fu_562_p3 == 1'd1) & (icmp_ln144_fu_556_p2 == 1'd0) & (icmp_ln141_fu_550_p2 == 1'd0))))) begin
        agg_result_1_0_reg_184 <= p_read4;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln77_reg_1197 == 1'd1))) begin
        agg_result_1_0_reg_184 <= grp_fu_395_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln104_fu_951_p2 == 1'd0) & (icmp_ln92_reg_1279 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        agg_result_1_3_reg_204 <= grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_agg_result_1_1_out;
    end else if (((icmp_ln92_fu_899_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        agg_result_1_3_reg_204 <= agg_result_1_0_reg_184;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln77_1_fu_886_p2) & (1'b1 == ap_CS_fsm_state17))) begin
        agg_result_1_6_reg_259 <= agg_result_1_0_reg_184;
    end else if (((icmp_ln104_fu_951_p2 == 1'd1) & (icmp_ln92_reg_1279 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        agg_result_1_6_reg_259 <= grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_agg_result_1_1_out;
    end else if ((((1'b1 == ap_CS_fsm_state3) & (((icmp_ln61_8_reg_1161 == 1'd0) & (icmp_ln144_fu_556_p2 == 1'd1) & (icmp_ln141_fu_550_p2 == 1'd0)) | ((1'd0 == and_ln61_4_fu_536_p2) & (icmp_ln144_fu_556_p2 == 1'd1) & (icmp_ln141_fu_550_p2 == 1'd0)))) | ((1'd1 == and_ln61_fu_490_p2) & (icmp_ln61_reg_1148 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        agg_result_1_6_reg_259 <= p_read4;
    end else if (((1'b1 == ap_CS_fsm_state23) & (((((((((1'd0 == and_ln61_4_reg_1165) & (1'd0 == and_ln61_reg_1157) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0)) | ((1'd0 == and_ln61_4_reg_1165) & (1'd0 == and_ln61_reg_1157) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_reg_1157) & (icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_reg_1157) & (icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_4_reg_1165) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_4_reg_1165) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))))) begin
        agg_result_1_6_reg_259 <= grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_agg_result_1_4_out;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        agg_result_1_6_reg_259 <= bitcast_ln136_fu_1030_p1;
    end else if (((grp_p_sum_1_fu_346_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        agg_result_1_6_reg_259 <= grp_p_sum_1_fu_346_ap_return_1;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        agg_result_1_6_reg_259 <= bitcast_ln142_fu_1018_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln104_fu_951_p2 == 1'd0) & (icmp_ln92_reg_1279 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        base_0_lcssa_i_i1013_reg_236 <= base_fu_929_p2;
    end else if (((icmp_ln92_fu_899_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        base_0_lcssa_i_i1013_reg_236 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln61_8_reg_1161 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        and_ln61_4_reg_1165 <= and_ln61_4_fu_536_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln61_reg_1148 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        and_ln61_reg_1157 <= and_ln61_fu_490_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        and_ln77_1_reg_1269 <= and_ln77_1_fu_886_p2;
        tmp_55_reg_1261 <= grp_fu_395_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        c_p_reg_1140 <= c_p_fu_439_p1;
        icmp_ln61_reg_1148 <= icmp_ln61_fu_443_p2;
        trunc_ln129_reg_1135 <= trunc_ln129_fu_435_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (((icmp_ln61_8_reg_1161 == 1'd0) & (tmp_fu_562_p3 == 1'd1) & (icmp_ln144_fu_556_p2 == 1'd0) & (icmp_ln141_fu_550_p2 == 1'd0)) | ((1'd0 == and_ln61_4_fu_536_p2) & (tmp_fu_562_p3 == 1'd1) & (icmp_ln144_fu_556_p2 == 1'd0) & (icmp_ln141_fu_550_p2 == 1'd0))))) begin
        diff_p_1_reg_1192 <= diff_p_1_fu_570_p2;
        icmp_ln77_reg_1197 <= icmp_ln77_fu_576_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & ((1'd0 == and_ln61_4_fu_536_p2) | (icmp_ln61_8_reg_1161 == 1'd0)))) begin
        diff_p_reg_1169 <= diff_p_fu_542_p2;
        icmp_ln141_reg_1180 <= icmp_ln141_fu_550_p2;
        trunc_ln138_reg_1175 <= trunc_ln138_fu_546_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        empty_reg_1273 <= empty_fu_894_p1;
        icmp_ln92_reg_1279 <= icmp_ln92_fu_899_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln92_reg_1279 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        icmp_ln104_reg_1303 <= icmp_ln104_fu_951_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (((icmp_ln61_8_reg_1161 == 1'd0) & (icmp_ln141_fu_550_p2 == 1'd0)) | ((1'd0 == and_ln61_4_fu_536_p2) & (icmp_ln141_fu_550_p2 == 1'd0))))) begin
        icmp_ln144_reg_1184 <= icmp_ln144_fu_556_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & ((1'd0 == and_ln61_fu_490_p2) | (icmp_ln61_reg_1148 == 1'd0)))) begin
        icmp_ln61_8_reg_1161 <= icmp_ln61_8_fu_496_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state21) & ((icmp_ln104_fu_951_p2 == 1'd0) | (icmp_ln92_reg_1279 == 1'd0)))) begin
        select_ln104_reg_1307 <= select_ln104_fu_973_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        tmp_52_reg_1232 <= diff_p_1_reg_1192[32'd1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (((icmp_ln61_8_reg_1161 == 1'd0) & (icmp_ln144_fu_556_p2 == 1'd0) & (icmp_ln141_fu_550_p2 == 1'd0)) | ((1'd0 == and_ln61_4_fu_536_p2) & (icmp_ln144_fu_556_p2 == 1'd0) & (icmp_ln141_fu_550_p2 == 1'd0))))) begin
        tmp_reg_1188 <= diff_p_fu_542_p2[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (tmp_52_fu_647_p3 == 1'd0))) begin
        trunc_ln117_1_reg_1236 <= trunc_ln117_1_fu_744_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        trunc_ln117_4_reg_1251 <= trunc_ln117_4_fu_836_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (((icmp_ln61_8_reg_1161 == 1'd0) & (icmp_ln77_fu_576_p2 == 1'd1) & (tmp_fu_562_p3 == 1'd1) & (icmp_ln144_fu_556_p2 == 1'd0) & (icmp_ln141_fu_550_p2 == 1'd0)) | ((1'd0 == and_ln61_4_fu_536_p2) & (icmp_ln77_fu_576_p2 == 1'd1) & (tmp_fu_562_p3 == 1'd1) & (icmp_ln144_fu_556_p2 == 1'd0) & (icmp_ln141_fu_550_p2 == 1'd0))))) begin
        trunc_ln117_reg_1202 <= trunc_ln117_fu_619_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln92_fu_899_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        xor_ln92_reg_1283 <= xor_ln92_fu_905_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_ap_done == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_ap_done == 1'b0)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

assign ap_ST_fsm_state21_blk = 1'b0;

always @ (*) begin
    if ((grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_ap_done == 1'b0)) begin
        ap_ST_fsm_state22_blk = 1'b1;
    end else begin
        ap_ST_fsm_state22_blk = 1'b0;
    end
end

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_p_sum_1_fu_346_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) & (((((((((1'd0 == and_ln61_4_reg_1165) & (1'd0 == and_ln61_reg_1157) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0)) | ((1'd0 == and_ln61_4_reg_1165) & (1'd0 == and_ln61_reg_1157) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_reg_1157) & (icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_reg_1157) & (icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_4_reg_1165) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_4_reg_1165) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))))) begin
        ap_phi_mux_agg_result_01_4_phi_fu_327_p16 = agg_result_01_0_reg_248;
    end else begin
        ap_phi_mux_agg_result_01_4_phi_fu_327_p16 = agg_result_01_4_reg_324;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) & (((((((((1'd0 == and_ln61_4_reg_1165) & (1'd0 == and_ln61_reg_1157) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0)) | ((1'd0 == and_ln61_4_reg_1165) & (1'd0 == and_ln61_reg_1157) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_reg_1157) & (icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_reg_1157) & (icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_4_reg_1165) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_4_reg_1165) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))))) begin
        ap_phi_mux_agg_result_112_6_phi_fu_284_p16 = grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_agg_result_112_3_out;
    end else begin
        ap_phi_mux_agg_result_112_6_phi_fu_284_p16 = agg_result_112_6_reg_281;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) & (((((((((1'd0 == and_ln61_4_reg_1165) & (1'd0 == and_ln61_reg_1157) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0)) | ((1'd0 == and_ln61_4_reg_1165) & (1'd0 == and_ln61_reg_1157) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_reg_1157) & (icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_reg_1157) & (icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_4_reg_1165) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_4_reg_1165) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))))) begin
        ap_phi_mux_agg_result_12_5_phi_fu_306_p16 = grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_agg_result_12_3_out;
    end else begin
        ap_phi_mux_agg_result_12_5_phi_fu_306_p16 = agg_result_12_5_reg_303;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) & (((((((((1'd0 == and_ln61_4_reg_1165) & (1'd0 == and_ln61_reg_1157) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0)) | ((1'd0 == and_ln61_4_reg_1165) & (1'd0 == and_ln61_reg_1157) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_reg_1157) & (icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_reg_1157) & (icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_4_reg_1165) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((1'd0 == and_ln61_4_reg_1165) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln104_reg_1303 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))) | ((icmp_ln61_8_reg_1161 == 1'd0) & (1'd1 == and_ln77_1_reg_1269) & (icmp_ln61_reg_1148 == 1'd0) & (icmp_ln92_reg_1279 == 1'd0) & (tmp_reg_1188 == 1'd1) & (icmp_ln144_reg_1184 == 1'd0) & (icmp_ln141_reg_1180 == 1'd0))))) begin
        ap_phi_mux_agg_result_1_6_phi_fu_262_p16 = grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_agg_result_1_4_out;
    end else begin
        ap_phi_mux_agg_result_1_6_phi_fu_262_p16 = agg_result_1_6_reg_259;
    end
end

always @ (*) begin
    if (((icmp_ln104_fu_951_p2 == 1'd0) & (icmp_ln92_reg_1279 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        ap_phi_mux_base_0_lcssa_i_i1013_phi_fu_240_p4 = base_fu_929_p2;
    end else begin
        ap_phi_mux_base_0_lcssa_i_i1013_phi_fu_240_p4 = base_0_lcssa_i_i1013_reg_236;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        ap_return_0 = ap_phi_mux_agg_result_01_4_phi_fu_327_p16;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        ap_return_1 = ap_phi_mux_agg_result_1_6_phi_fu_262_p16;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        ap_return_2 = ap_phi_mux_agg_result_112_6_phi_fu_284_p16;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        ap_return_3 = ap_phi_mux_agg_result_12_5_phi_fu_306_p16;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_1342_ce = grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_grp_fu_1342_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_1342_ce = grp_p_sum_1_fu_346_grp_fu_1342_p_ce;
    end else begin
        grp_fu_1342_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_1342_opcode = grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_grp_fu_1342_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_1342_opcode = grp_p_sum_1_fu_346_grp_fu_1342_p_opcode;
    end else begin
        grp_fu_1342_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_1342_p0 = grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_grp_fu_1342_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_1342_p0 = grp_p_sum_1_fu_346_grp_fu_1342_p_din0;
    end else begin
        grp_fu_1342_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_1342_p1 = grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_grp_fu_1342_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_1342_p1 = grp_p_sum_1_fu_346_grp_fu_1342_p_din1;
    end else begin
        grp_fu_1342_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_395_ce = grp_p_sum_1_fu_346_grp_fu_395_p_ce;
    end else begin
        grp_fu_395_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_395_p0 = grp_p_sum_1_fu_346_grp_fu_395_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_395_p0 = bitcast_ln117_2_fu_840_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_395_p0 = bitcast_ln117_1_fu_748_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_395_p0 = bitcast_ln117_fu_642_p1;
    end else begin
        grp_fu_395_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_395_p1 = grp_p_sum_1_fu_346_grp_fu_395_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_395_p1 = p_read3;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_395_p1 = p_read25;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_395_p1 = p_read4;
    end else begin
        grp_fu_395_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_401_p0 = agg_result_1_0_reg_184;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_401_p0 = p_read4;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_401_p0 = bitcast_ln61_fu_449_p1;
    end else begin
        grp_fu_401_p0 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & ((1'd0 == and_ln61_fu_490_p2) | (icmp_ln61_reg_1148 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (((icmp_ln61_8_reg_1161 == 1'd0) & (icmp_ln77_fu_576_p2 == 1'd0) & (tmp_fu_562_p3 == 1'd1) & (icmp_ln144_fu_556_p2 == 1'd0) & (icmp_ln141_fu_550_p2 == 1'd0)) | ((1'd0 == and_ln61_4_fu_536_p2) & (icmp_ln77_fu_576_p2 == 1'd0) & (tmp_fu_562_p3 == 1'd1) & (icmp_ln144_fu_556_p2 == 1'd0) & (icmp_ln141_fu_550_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if (((1'b1 == ap_CS_fsm_state3) & (((icmp_ln61_8_reg_1161 == 1'd0) & (icmp_ln77_fu_576_p2 == 1'd1) & (tmp_fu_562_p3 == 1'd1) & (icmp_ln144_fu_556_p2 == 1'd0) & (icmp_ln141_fu_550_p2 == 1'd0)) | ((1'd0 == and_ln61_4_fu_536_p2) & (icmp_ln77_fu_576_p2 == 1'd1) & (tmp_fu_562_p3 == 1'd1) & (icmp_ln144_fu_556_p2 == 1'd0) & (icmp_ln141_fu_550_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else if (((1'b1 == ap_CS_fsm_state3) & (((icmp_ln61_8_reg_1161 == 1'd0) & (tmp_fu_562_p3 == 1'd0) & (icmp_ln144_fu_556_p2 == 1'd0) & (icmp_ln141_fu_550_p2 == 1'd0)) | ((1'd0 == and_ln61_4_fu_536_p2) & (tmp_fu_562_p3 == 1'd0) & (icmp_ln144_fu_556_p2 == 1'd0) & (icmp_ln141_fu_550_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if (((1'b1 == ap_CS_fsm_state3) & (((icmp_ln61_8_reg_1161 == 1'd0) & (icmp_ln144_fu_556_p2 == 1'd1) & (icmp_ln141_fu_550_p2 == 1'd0)) | ((1'd0 == and_ln61_4_fu_536_p2) & (icmp_ln144_fu_556_p2 == 1'd1) & (icmp_ln141_fu_550_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else if (((1'b1 == ap_CS_fsm_state3) & (((icmp_ln61_8_reg_1161 == 1'd0) & (icmp_ln141_fu_550_p2 == 1'd1)) | ((1'd0 == and_ln61_4_fu_536_p2) & (icmp_ln141_fu_550_p2 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_p_sum_1_fu_346_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (tmp_52_fu_647_p3 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((1'd0 == and_ln77_1_fu_886_p2) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((icmp_ln92_fu_899_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state20 : begin
            if (((grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            if (((icmp_ln104_fu_951_p2 == 1'd1) & (icmp_ln92_reg_1279 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state22 : begin
            if (((grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln104_fu_967_p2 = (zext_ln104_fu_957_p1 + 3'd1);

assign add_ln117_1_fu_654_p2 = (diff_p_reg_1169 + 32'd1);

assign add_ln117_2_fu_671_p2 = (zext_ln117_4_fu_667_p1 + 38'd32);

assign add_ln117_3_fu_681_p2 = (zext_ln117_4_fu_667_p1 + 38'd64);

assign add_ln117_4_fu_767_p2 = (zext_ln117_7_fu_763_p1 + 7'd32);

assign add_ln117_fu_592_p2 = (zext_ln117_fu_588_p1 + 38'd32);

assign and_ln117_1_fu_733_p2 = (sub_ln117_fu_727_p2 & p_read13);

assign and_ln117_2_fu_821_p2 = (trunc_ln129_reg_1135 & sub_ln117_1_fu_815_p2);

assign and_ln117_fu_608_p2 = (shl_ln117_fu_602_p2 & p_read13);

assign and_ln61_4_fu_536_p2 = (or_ln61_1_fu_530_p2 & grp_fu_401_p2);

assign and_ln61_fu_490_p2 = (or_ln61_fu_484_p2 & grp_fu_401_p2);

assign and_ln77_1_fu_886_p2 = (icmp_ln77_reg_1197 & and_ln77_fu_880_p2);

assign and_ln77_fu_880_p2 = (or_ln77_fu_874_p2 & grp_fu_401_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign base_fu_929_p2 = (sub_ln92_fu_924_p2 + 2'd1);

assign bitcast_ln117_1_fu_748_p1 = trunc_ln117_1_reg_1236;

assign bitcast_ln117_2_fu_840_p1 = trunc_ln117_4_reg_1251;

assign bitcast_ln117_fu_642_p1 = zext_ln117_2_fu_639_p1;

assign bitcast_ln136_1_fu_1034_p1 = grp_fu_417_p4;

assign bitcast_ln136_2_fu_1038_p1 = grp_fu_426_p4;

assign bitcast_ln136_fu_1030_p1 = grp_fu_407_p4;

assign bitcast_ln142_1_fu_1022_p1 = grp_fu_417_p4;

assign bitcast_ln142_2_fu_1026_p1 = grp_fu_426_p4;

assign bitcast_ln142_fu_1018_p1 = grp_fu_407_p4;

assign bitcast_ln61_1_fu_501_p1 = p_read4;

assign bitcast_ln61_fu_449_p1 = grp_fu_407_p4;

assign bitcast_ln77_fu_844_p1 = agg_result_1_0_reg_184;

assign c_p_fu_439_p1 = p_read13[31:0];

assign diff_p_1_fu_570_p2 = (2'd0 - trunc_ln138_fu_546_p1);

assign diff_p_fu_542_p2 = (c_p_reg_1140 - b_p_read);

assign empty_fu_894_p1 = grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_idx_tmp_out[1:0];

assign grp_fu_407_p4 = {{p_read13[63:32]}};

assign grp_fu_417_p4 = {{p_read13[95:64]}};

assign grp_fu_426_p4 = {{p_read13[127:96]}};

assign grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_ap_start = grp_operator_3_Pipeline_VITIS_LOOP_104_3_fu_379_ap_start_reg;

assign grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_ap_start = grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_ap_start_reg;

assign grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_ap_start = grp_operator_3_Pipeline_VITIS_LOOP_92_2_fu_365_ap_start_reg;

assign grp_p_sum_1_fu_346_ap_start = grp_p_sum_1_fu_346_ap_start_reg;

assign icmp_ln104_4_fu_961_p2 = ((ap_phi_mux_base_0_lcssa_i_i1013_phi_fu_240_p4 != 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln104_fu_951_p2 = ((base_fu_929_p2 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln117_fu_707_p2 = ((tmp_53_fu_697_p4 != 31'd0) ? 1'b1 : 1'b0);

assign icmp_ln141_fu_550_p2 = (($signed(diff_p_fu_542_p2) > $signed(32'd2)) ? 1'b1 : 1'b0);

assign icmp_ln144_fu_556_p2 = (($signed(diff_p_fu_542_p2) < $signed(32'd4294967294)) ? 1'b1 : 1'b0);

assign icmp_ln61_10_fu_478_p2 = ((trunc_ln61_3_fu_463_p4 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln61_11_fu_518_p2 = ((tmp_49_fu_504_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln61_12_fu_524_p2 = ((trunc_ln61_1_fu_514_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln61_8_fu_496_p2 = ((b_p_read == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln61_9_fu_472_p2 = ((tmp_s_fu_454_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_443_p2 = ((c_p_fu_439_p1 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln77_4_fu_862_p2 = ((tmp_56_fu_848_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln77_5_fu_868_p2 = ((trunc_ln77_fu_858_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln77_fu_576_p2 = ((c_p_reg_1140 == b_p_read) ? 1'b1 : 1'b0);

assign icmp_ln92_fu_899_p2 = ((grp_operator_3_Pipeline_VITIS_LOOP_84_1_fu_355_idx_tmp_out < 32'd3) ? 1'b1 : 1'b0);

assign lshr_ln117_1_fu_738_p2 = and_ln117_1_fu_733_p2 >> zext_ln117_3_fu_677_p1;

assign lshr_ln117_2_fu_830_p2 = zext_ln117_11_fu_826_p1 >> zext_ln117_6_fu_773_p1;

assign lshr_ln117_fu_613_p2 = and_ln117_fu_608_p2 >> zext_ln117_1_fu_598_p1;

assign or_ln61_1_fu_530_p2 = (icmp_ln61_12_fu_524_p2 | icmp_ln61_11_fu_518_p2);

assign or_ln61_fu_484_p2 = (icmp_ln61_9_fu_472_p2 | icmp_ln61_10_fu_478_p2);

assign or_ln77_fu_874_p2 = (icmp_ln77_5_fu_868_p2 | icmp_ln77_4_fu_862_p2);

assign or_ln_fu_781_p4 = {{{{1'd1}, {trunc_ln117_2_fu_752_p1}}}, {5'd0}};

assign select_ln104_fu_973_p3 = ((icmp_ln104_4_fu_961_p2[0:0] == 1'b1) ? 3'd3 : add_ln104_fu_967_p2);

assign select_ln117_fu_713_p3 = ((icmp_ln117_fu_707_p2[0:0] == 1'b1) ? 128'd0 : shl_ln117_1_fu_691_p2);

assign sext_ln100_fu_942_p1 = $signed(xor_ln100_fu_936_p2);

assign shl_ln117_1_fu_691_p2 = 128'd1 << zext_ln117_5_fu_687_p1;

assign shl_ln117_2_fu_659_p3 = {{add_ln117_1_fu_654_p2}, {5'd0}};

assign shl_ln117_3_fu_721_p2 = 128'd1 << zext_ln117_3_fu_677_p1;

assign shl_ln117_4_fu_795_p2 = 97'd1 << zext_ln117_9_fu_791_p1;

assign shl_ln117_5_fu_755_p3 = {{trunc_ln117_2_fu_752_p1}, {5'd0}};

assign shl_ln117_6_fu_805_p2 = 65'd1 << zext_ln117_8_fu_777_p1;

assign shl_ln117_fu_602_p2 = 128'd340282366920938463463374607431768211455 << zext_ln117_1_fu_598_p1;

assign shl_ln_fu_580_p3 = {{diff_p_fu_542_p2}, {5'd0}};

assign sub_ln117_1_fu_815_p2 = (trunc_ln117_3_fu_801_p1 - zext_ln117_10_fu_811_p1);

assign sub_ln117_fu_727_p2 = (select_ln117_fu_713_p3 - shl_ln117_3_fu_721_p2);

assign sub_ln92_fu_924_p2 = ($signed(2'd2) - $signed(empty_reg_1273));

assign tmp_49_fu_504_p4 = {{bitcast_ln61_1_fu_501_p1[30:23]}};

assign tmp_52_fu_647_p3 = diff_p_1_reg_1192[32'd1];

assign tmp_53_fu_697_p4 = {{add_ln117_3_fu_681_p2[37:7]}};

assign tmp_56_fu_848_p4 = {{bitcast_ln77_fu_844_p1[30:23]}};

assign tmp_59_fu_946_p2 = ($signed(sext_ln100_fu_942_p1) + $signed(b_p_read));

assign tmp_fu_562_p3 = diff_p_fu_542_p2[32'd31];

assign tmp_s_fu_454_p4 = {{p_read13[62:55]}};

assign trunc_ln117_1_fu_744_p1 = lshr_ln117_1_fu_738_p2[31:0];

assign trunc_ln117_2_fu_752_p1 = diff_p_reg_1169[0:0];

assign trunc_ln117_3_fu_801_p1 = shl_ln117_4_fu_795_p2[95:0];

assign trunc_ln117_4_fu_836_p1 = lshr_ln117_2_fu_830_p2[31:0];

assign trunc_ln117_fu_619_p1 = lshr_ln117_fu_613_p2[0:0];

assign trunc_ln129_fu_435_p1 = p_read13[95:0];

assign trunc_ln138_fu_546_p1 = diff_p_fu_542_p2[1:0];

assign trunc_ln61_1_fu_514_p1 = bitcast_ln61_1_fu_501_p1[22:0];

assign trunc_ln61_3_fu_463_p4 = {{p_read13[54:32]}};

assign trunc_ln77_fu_858_p1 = bitcast_ln77_fu_844_p1[22:0];

assign xor_ln100_fu_936_p2 = (sub_ln92_fu_924_p2 ^ 2'd2);

assign xor_ln92_fu_905_p2 = (empty_fu_894_p1 ^ 2'd3);

assign zext_ln104_fu_957_p1 = ap_phi_mux_base_0_lcssa_i_i1013_phi_fu_240_p4;

assign zext_ln117_10_fu_811_p1 = shl_ln117_6_fu_805_p2;

assign zext_ln117_11_fu_826_p1 = and_ln117_2_fu_821_p2;

assign zext_ln117_1_fu_598_p1 = add_ln117_fu_592_p2;

assign zext_ln117_2_fu_639_p1 = trunc_ln117_reg_1202;

assign zext_ln117_3_fu_677_p1 = add_ln117_2_fu_671_p2;

assign zext_ln117_4_fu_667_p1 = shl_ln117_2_fu_659_p3;

assign zext_ln117_5_fu_687_p1 = add_ln117_3_fu_681_p2;

assign zext_ln117_6_fu_773_p1 = add_ln117_4_fu_767_p2;

assign zext_ln117_7_fu_763_p1 = shl_ln117_5_fu_755_p3;

assign zext_ln117_8_fu_777_p1 = add_ln117_4_fu_767_p2;

assign zext_ln117_9_fu_791_p1 = or_ln_fu_781_p4;

assign zext_ln117_fu_588_p1 = shl_ln_fu_580_p3;

endmodule //ban_interface_operator_3
